# Generated by Django 5.2.3 on 2025-07-29 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_delete_studentpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('added_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'staff_profile__can_confirm_transactions': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Transacción de Estudiante',
                'verbose_name_plural': 'Transacciones de Estudiantes',
                'db_table': 'student_transactions_db',
                'ordering': ['-date_added', 'student_profile__user__national_id'],
            },
        ),
    ]
