# Generated by Django 5.2.3 on 2025-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(choices=[('VUELO', 'Vuelo'), ('SIMULADOR', 'Simulador')], default='VUELO', max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
