# Generated by Django 5.2.3 on 2025-08-20 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_studentpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(choices=[('VUELO', 'Vuelo'), ('SIMULADOR', 'Simulador'), ('DEBITO', 'Débito')], default='VUELO', max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
