# Generated by Django 5.2.3 on 2025-09-17 17:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_studentpayment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'ordering': ['-date_added', 'student_profile__user__national_id'], 'verbose_name': 'Transacción de Estudiante', 'verbose_name_plural': 'Transacciones de Estudiantes'},
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='category',
            field=models.CharField(choices=[('N/A', 'N/A'), ('VUELO', 'Vuelo'), ('SIMULADOR', 'Simulador'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], default='N/A', max_length=20, verbose_name='Categoría de transacción'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de transacción'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], default='CREDITO', max_length=20, verbose_name='Tipo de transacción'),
        ),
        migrations.AlterModelTable(
            name='studentpayment',
            table='student_transactions_db',
        ),
    ]
