# Generated by Django 5.2.3 on 2025-09-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_staffprofile_can_confirm_payments_and_more'),
        ('transactions', '0006_rename_studentpayment_to_studenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__can_confirm_payments': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='studenttransaction',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.studentprofile', verbose_name='Estudiante'),
        ),
        migrations.AlterModelTable(
            name='studenttransaction',
            table='student_transactions_db',
        ),
    ]
