# Generated by Django 5.2.3 on 2025-09-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_studenttransaction_confirmed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__can_confirm_transactions': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
