# Generated by Django 5.2.3 on 2025-09-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_studenttransaction_confirmed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
