# Generated by Django 5.2.3 on 2025-11-14 20:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_instructorprofile_instructor_hourly_rate'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('transactions', '0009_alter_studenttransaction_confirmed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de evaluación')),
                ('fuel_volume', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Volumen de combustible (litros)')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de transacción')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('added_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fuel_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['flightevaluation0_100', 'flightevaluation100_120', 'flightevaluation120_170']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de evaluación')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='accounts.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Transacción de Combustible',
                'verbose_name_plural': 'Transacciones de Combustible',
                'db_table': 'fuel_transactions_db',
                'ordering': ['-date_added', 'student_profile__user__national_id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='fuel_transa_content_6b27ad_idx')],
            },
        ),
    ]
