# Generated by Django 5.2.3 on 2025-11-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_fueltransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelTransaction',
        ),
    ]
