# Generated by Django 5.2.3 on 2026-09-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0065_update_flight_instructor_rate_snapshots'),
        ('transactions', '0011_remove_fuel_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransaction',
            name='fuel_flight_0_100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_fuel_transactions', to='fms.flightevaluation0_100'),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='fuel_flight_100_120',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_fuel_transactions', to='fms.flightevaluation100_120'),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='fuel_flight_120_170',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_fuel_transactions', to='fms.flightevaluation120_170'),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='fuel_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='fuel_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
