# Generated by Django 5.2.3 on 2026-09-29 21:20

from django.db import migrations, models


def mark_existing_late_fuel(apps, schema_editor):
    """Label existing fuel snapshots so their audit meaning is explicit."""
    StudentTransaction = apps.get_model('transactions', 'StudentTransaction')
    StudentTransaction.objects.filter(fuel_liters__isnull=False).update(
        flight_activity_type='LATE_FUEL',
    )


def unmark_existing_late_fuel(apps, schema_editor):
    """Restore the blank value used before activity types existed."""
    StudentTransaction = apps.get_model('transactions', 'StudentTransaction')
    StudentTransaction.objects.filter(flight_activity_type='LATE_FUEL').update(
        flight_activity_type='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_link_identifiable_historical_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransaction',
            name='flight_activity_type',
            field=models.CharField(blank=True, choices=[('LATE_FUEL', 'Combustible registrado posteriormente'), ('FUEL_CORRECTION', 'Corrección de combustible'), ('HOURS_CORRECTION', 'Corrección de tiempo de vuelo')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='flight_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RunPython(mark_existing_late_fuel, unmark_existing_late_fuel),
    ]
