# Generated by Django 5.2.3 on 2025-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=20, unique=True, verbose_name='Incident Number')),
                ('title', models.CharField(max_length=200, verbose_name='Incident Title')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('incident_date', models.DateField(verbose_name='Date of Incident')),
                ('incident_time', models.TimeField(verbose_name='Time of Incident')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('severity', models.CharField(choices=[('LOW', 'Low - No damage, minor injury'), ('MEDIUM', 'Medium - Minor damage, minor injury'), ('HIGH', 'High - Major damage, serious injury'), ('CRITICAL', 'Critical - Fatal injury, aircraft destroyed')], default='LOW', max_length=20, verbose_name='Severity Level')),
                ('category', models.CharField(choices=[('FLIGHT_OPERATIONS', 'Flight Operations'), ('MAINTENANCE', 'Maintenance'), ('GROUND_OPERATIONS', 'Ground Operations'), ('TRAINING', 'Training'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Incident Category')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='Reporter Name')),
                ('reporter_contact', models.CharField(blank=True, max_length=100, verbose_name='Reporter Contact')),
                ('people_involved', models.TextField(blank=True, verbose_name='People Involved')),
                ('aircraft_registration', models.CharField(blank=True, max_length=10, verbose_name='Aircraft Registration')),
                ('damage_description', models.TextField(blank=True, verbose_name='Damage Description')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Cost (USD)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='Investigation Notes')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Corrective Actions')),
                ('preventive_measures', models.TextField(blank=True, verbose_name='Preventive Measures')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Safety Incident',
                'verbose_name_plural': 'Safety Incidents',
                'ordering': ['-incident_date', '-incident_time'],
            },
        ),
    ]
