# Generated by Django 5.2.3 on 2025-11-22 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntaryHazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.CharField(choices=[('YES', 'SI'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Reporte anónimo')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido')),
                ('role', models.CharField(blank=True, choices=[('DIRECTOR', 'Dirección'), ('OPERATIONS', 'Operaciones'), ('GROUND_INSTRUCTOR', 'Instructor de tierra'), ('FLIGHT_INSTRUCTOR', 'Instructor de vuelo'), ('STUDENT', 'Alumno'), ('ADMIN', 'Administrativo'), ('OTHER', 'Otro')], default='', max_length=20, null=True, verbose_name='Cargo o función')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='Hora')),
                ('area', models.CharField(choices=[('ADMIN', 'Sede administrativa'), ('PLATFORM', 'Plataforma'), ('AIRPORT_OFFICE', 'Ofic. Aeropuerto'), ('OPERATIONS', 'Operaciones'), ('OTHER', 'Otro')], default='OPERATIONS', max_length=20, verbose_name='Área del peligro')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción del peligro')),
                ('ai_analysis_status', models.CharField(choices=[('PENDING', 'Pendiente de análisis'), ('PROCESSING', 'Analizando con IA'), ('COMPLETED', 'Análisis completado'), ('FAILED', 'Error en análisis')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado del análisis de IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Reporte de peligro voluntario',
                'verbose_name_plural': 'Reportes de peligro voluntarios',
            },
        ),
    ]
