# Generated by Django 5.2.3 on 2025-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyincident',
            options={'verbose_name': 'Safety Incident', 'verbose_name_plural': 'Safety Incidents'},
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='aircraft_registration',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='category',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='corrective_actions',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='damage_description',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='incident_number',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='incident_time',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='investigation_notes',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='people_involved',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='preventive_measures',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='reported_at',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='reporter_contact',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='reporter_name',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='safetyincident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='safetyincident',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='AI Analysis'),
        ),
    ]
