# Generated by Django 5.2.3 on 2025-08-12 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_safetyincident_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='voluntary_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo o función que ocupa en la institución')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('area', models.CharField(choices=[('ADMIN', 'Sede administrativa'), ('PLATFORM', 'Plataforma'), ('AIRPORT_OFFICE', 'Ofic. Aeropuerto'), ('OPERATIONS', 'Operaciones'), ('OTHER', 'Otro')], default='OPERATIONS', max_length=20, verbose_name='Área del peligro')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción del peligro')),
                ('report_condition', models.BooleanField(default=False, verbose_name='Condición del reporte')),
                ('invalid_reason', models.TextField(max_length=200, verbose_name='Motivo de invalidación')),
                ('coordinator_first_name', models.CharField(max_length=200, verbose_name='Nombre del coordinador')),
                ('coordinator_last_name', models.CharField(max_length=200, verbose_name='Apellido del coordinador')),
                ('coordinator_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999), django.core.validators.MaxValueValidator(100000000)], verbose_name='Cédula')),
                ('report_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Código del reporte')),
                ('received_date', models.DateField(verbose_name='Fecha de recepción')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis AI')),
            ],
            options={
                'verbose_name': 'Reporte voluntario',
                'verbose_name_plural': 'Reportes voluntarios',
            },
        ),
        migrations.DeleteModel(
            name='SafetyIncident',
        ),
    ]
