# Generated by Django 5.2.3 on 2025-11-25 20:56

import django.db.models.deletion
import django.utils.timezone
import sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_voluntaryhazardreport_ai_analysis_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='human_validated',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AlterField(
            model_name='voluntaryhazardreport',
            name='ai_analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de análisis'), ('PROCESSING', 'Analizando con IA'), ('COMPLETED', 'Análisis completado'), ('FAILED', 'Error en análisis')], db_index=True, default='PENDING', max_length=20, verbose_name='IA Estatus'),
        ),
        migrations.AlterField(
            model_name='voluntaryhazardreport',
            name='area',
            field=models.CharField(choices=[('ADMIN', 'Sede administrativa'), ('PLATFORM', 'Plataforma'), ('AIRPORT_OFFICE', 'Ofic. Aeropuerto'), ('OPERATIONS', 'Operaciones'), ('OTHER', 'Otro')], default='OPERATIONS', max_length=20, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='voluntaryhazardreport',
            name='is_anonymous',
            field=models.CharField(choices=[('YES', 'SI'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Anónimo'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('pre_evaluation', models.CharField(max_length=2, verbose_name='Evaluación del riesgo sin mitigación')),
                ('post_evaluation', models.CharField(max_length=2, verbose_name='Evaluación del riesgo con mitigación')),
                ('status', models.CharField(choices=[('INTOLERABLE', 'Intolerable'), ('TOLERABLE', 'Tolerable'), ('ACCEPTABLE', 'Aceptable'), ('NOT_EVALUATED', 'No evaluado')], default='NOT_EVALUATED', max_length=15, verbose_name='Estatus del riesgo')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='sms.voluntaryhazardreport', verbose_name='Reporte Voluntario de Peligro')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
            },
        ),
        migrations.CreateModel(
            name='MitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Sin completar'), ('COMPLETED', 'Completada'), ('EXPIRED', 'Vencida')], default='PENDING', max_length=9, verbose_name='Estatus')),
                ('due_date', models.DateField(default=sms.models.default_due_date, verbose_name='Fecha límite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='sms.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Acción de mitigación',
                'verbose_name_plural': 'Acciones de mitigación',
            },
        ),
    ]
