# Generated by Django 5.2.3 on 2025-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_voluntary_report_delete_safetyincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntary_report',
            name='coordinator_first_name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='voluntary_report',
            name='coordinator_last_name',
            field=models.CharField(max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='voluntary_report',
            name='invalid_reason',
            field=models.TextField(help_text='En caso de no ser válido explique el motivo.', max_length=200, verbose_name='Motivo de invalidación'),
        ),
        migrations.AlterField(
            model_name='voluntary_report',
            name='report_condition',
            field=models.BooleanField(default=False, verbose_name='Validez del reporte'),
        ),
    ]
