# Generated by Django 5.2.3 on 2025-08-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_voluntary_report_coordinator_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntary_report',
            name='ai_analysis',
        ),
        migrations.CreateModel(
            name='report_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(verbose_name='¿Es un reporte de seguridad válido?')),
                ('severity', models.CharField(max_length=1, verbose_name='Nivel de severidad')),
                ('probability', models.CharField(max_length=1, verbose_name='Nivel de probabilidad')),
                ('value', models.CharField(help_text='Combinación de severidad y probabilidad (ej: C4, D3)', max_length=2, verbose_name='Valor alfanumérico')),
                ('risk_analysis', models.TextField(max_length=5000, verbose_name='Análisis de riesgos')),
                ('recommendations', models.TextField(max_length=5000, verbose_name='Recomendaciones')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.voluntary_report')),
            ],
            options={
                'verbose_name': 'Análisis de reporte',
                'verbose_name_plural': 'Análisis de reportes',
            },
        ),
    ]
