# Generated by Django 5.2.3 on 2025-08-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_remove_voluntary_report_ai_analysis_report_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntary_report',
            name='coordinator_first_name',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='coordinator_id',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='coordinator_last_name',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='invalid_reason',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='report_code',
        ),
        migrations.RemoveField(
            model_name='voluntary_report',
            name='report_condition',
        ),
    ]
