# Generated by Django 5.2.3 on 2025-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_remove_risk_post_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Es válido'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='post_evaluation_probability',
            field=models.CharField(choices=[('0', '-'), ('1', '1 - Sumamente improbable'), ('2', '2 - Improbable'), ('3', '3 - Remota'), ('4', '4 - Ocasional'), ('5', '5 - Frecuente')], default='0', max_length=1, verbose_name='Probabilidad post-mitigación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='post_evaluation_severity',
            field=models.CharField(choices=[('0', '-'), ('A', 'A - Catastrófico'), ('B', 'B - Peligroso'), ('C', 'C - Grave'), ('D', 'D - Leve'), ('E', 'E - Insignificante')], default='0', max_length=1, verbose_name='Severidad post-mitigación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pre_evaluation_probability',
            field=models.CharField(choices=[('0', '-'), ('1', '1 - Sumamente improbable'), ('2', '2 - Improbable'), ('3', '3 - Remota'), ('4', '4 - Ocasional'), ('5', '5 - Frecuente')], default='0', max_length=1, verbose_name='Probabilidad pre-mitigación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pre_evaluation_severity',
            field=models.CharField(choices=[('0', '-'), ('A', 'A - Catastrófico'), ('B', 'B - Peligroso'), ('C', 'C - Grave'), ('D', 'D - Leve'), ('E', 'E - Insignificante')], default='0', max_length=1, verbose_name='Severidad pre-mitigación'),
        ),
    ]
