# Generated by Django 5.2.3 on 2025-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_remove_voluntary_report_coordinator_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_analysis',
            name='is_valid',
            field=models.CharField(choices=[('YES', 'SI'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Es válido'),
        ),
    ]
