# Generated by Django 5.2.3 on 2025-11-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_voluntaryhazardreport_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='invalidity_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de invalidación'),
        ),
    ]
