# Generated by Django 5.2.3 on 2025-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_alter_report_analysis_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de análisis'),
        ),
        migrations.AddField(
            model_name='voluntary_report',
            name='ai_analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de análisis'), ('PROCESSING', 'Analizando con IA'), ('COMPLETED', 'Análisis completado'), ('FAILED', 'Error en análisis')], default='PENDING', max_length=20, verbose_name='Estado del análisis de IA'),
        ),
        migrations.AddField(
            model_name='voluntary_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='voluntary_report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
