# Generated by Django 5.2.3 on 2025-08-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_report_analysis_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntary_report',
            name='ai_analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de análisis'), ('PROCESSING', 'Analizando con IA'), ('COMPLETED', 'Análisis completado'), ('FAILED', 'Error en análisis')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado del análisis de IA'),
        ),
    ]
