# Generated by Django 5.2.3 on 2025-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_voluntaryhazardreport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntaryhazardreport',
            name='code',
            field=models.CharField(blank=True, help_text='Código de entrada para la BD del SMS', max_length=100, null=True, unique=True, verbose_name='Código'),
        ),
    ]
