# Generated by Django 5.2.3 on 2025-08-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_add_ai_analysis_status_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report_analysis',
            new_name='ReportAnalysis',
        ),
        migrations.RenameModel(
            old_name='voluntary_report',
            new_name='VoluntaryReport',
        ),
    ]
