# Generated by Django 5.2.3 on 2025-11-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_voluntaryhazardreport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='analysis_email_sent',
            field=models.BooleanField(default=False, help_text='Indica si se ha enviado el email de notificación cuando el análisis fue completado', verbose_name='Email de análisis enviado'),
        ),
    ]
