# Generated by Django 5.2.3 on 2025-12-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_voluntaryhazardreport_analysis_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntaryhazardreport',
            options={'verbose_name': 'RVP', 'verbose_name_plural': 'RVP'},
        ),
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='mmrs_created',
            field=models.BooleanField(default=False, help_text='Indica si se han creado las MMRs para el reporte', verbose_name='MMRs creadas'),
        ),
    ]
