# Generated by Django 5.2.3 on 2025-08-28 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_rename_report_analysis_reportanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryreport',
            name='is_anonymous',
            field=models.CharField(choices=[('YES', 'SI'), ('NO', 'NO')], default='NO', max_length=3, verbose_name='Reporte anónimo'),
        ),
        migrations.AlterField(
            model_name='voluntaryreport',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 28), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='voluntaryreport',
            name='time',
            field=models.TimeField(default=datetime.time(2, 50, 50, 619331), verbose_name='Hora'),
        ),
    ]
