# Generated by Django 5.2.3 on 2025-12-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_alter_voluntaryhazardreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='condition',
            field=models.CharField(choices=[('UNMITIGATED', 'Sin mitigar'), ('MITIGATED', 'Mitigado')], default='UNMITIGATED', max_length=20, verbose_name='Condición'),
        ),
    ]
