# Generated by Django 5.2.3 on 2025-08-28 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_voluntaryreport_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntaryreport',
            name='time',
            field=models.TimeField(default=datetime.time(2, 57, 9, 358604), verbose_name='Hora'),
        ),
    ]
