# Generated by Django 5.2.3 on 2025-08-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_voluntaryreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntaryreport',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Dirección'), ('OPERATIONS', 'Operaciones'), ('GROUND_INSTRUCTOR', 'Instructor de tierra'), ('FLIGHT_INSTRUCTOR', 'Instructor de vuelo'), ('STUDENT', 'Alumno'), ('ADMIN', 'Administrativo'), ('OTHER', 'Otro')], default='OTHER', max_length=20, null=True, verbose_name='Cargo o función'),
        ),
        migrations.AlterField(
            model_name='voluntaryreport',
            name='time',
            field=models.TimeField(default=datetime.time(10, 58, 36, 284899), verbose_name='Hora'),
        ),
    ]
