# Generated by Django 5.2.3 on 2025-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_risk_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitigationaction',
            options={'verbose_name': 'MMR', 'verbose_name_plural': 'MMR'},
        ),
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Indica si el reporte ha sido resuelto', verbose_name='Resuelto'),
        ),
    ]
