# Generated by Django 5.2.3 on 2025-08-28 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_voluntaryreport_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntaryreport',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Dirección'), ('OPERATIONS', 'Operaciones'), ('GROUND_INSTRUCTOR', 'Instructor de tierra'), ('FLIGHT_INSTRUCTOR', 'Instructor de vuelo'), ('STUDENT', 'Alumno'), ('ADMIN', 'Administrativo'), ('OTHER', 'Otro')], default='', max_length=20, null=True, verbose_name='Cargo o función'),
        ),
        migrations.AlterField(
            model_name='voluntaryreport',
            name='time',
            field=models.TimeField(default=datetime.time(11, 2, 29, 747862), verbose_name='Hora'),
        ),
    ]
