# Generated by Django 5.2.3 on 2025-12-08 15:29

import django.db.models.deletion
import django.utils.timezone
import sms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_mitigationaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigationaction',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='mitigationaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=9, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='voluntaryhazardreport',
            name='ai_analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Analizando'), ('COMPLETED', 'Completado'), ('FAILED', 'Error')], db_index=True, default='PENDING', max_length=20, verbose_name='IA Estatus'),
        ),
        migrations.CreateModel(
            name='MitigationActionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=9, verbose_name='Estatus')),
                ('due_date', models.DateField(default=sms.models.default_due_date, verbose_name='Fecha límite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='sms.mitigationaction', verbose_name='MMR')),
                ('responsible', models.ForeignKey(help_text='Solo usuarios con rol de Staff o Instructor pueden ser asignados como responsables', limit_choices_to=models.Q(('role', 'STAFF'), ('role', 'INSTRUCTOR'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Evidencia de MMR',
                'verbose_name_plural': 'Evidencias de MMR',
            },
        ),
    ]
