# Generated by Django 5.2.3 on 2025-08-28 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_voluntaryreport_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntaryreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='voluntaryreport',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='Hora'),
        ),
    ]
