# Generated by Django 5.2.3 on 2025-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_remove_mitigationaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitigationactionevidence',
            options={'verbose_name': 'Evidencia MMR', 'verbose_name_plural': 'Evidencias MMR'},
        ),
        migrations.RemoveField(
            model_name='voluntaryhazardreport',
            name='human_validated',
        ),
        migrations.RemoveField(
            model_name='voluntaryhazardreport',
            name='mmrs_created',
        ),
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Indica si se han creado las MMRs para el reporte', verbose_name='Procesado'),
        ),
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Registrado'),
        ),
        migrations.AlterField(
            model_name='mitigationaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], default='PENDING', max_length=9, verbose_name='Estatus'),
        ),
    ]
