# Generated by Django 5.2.3 on 2025-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_alter_voluntaryreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportanalysis',
            name='recommendations',
            field=models.JSONField(default=list, help_text='Lista de recomendaciones con relevance y text', verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='reportanalysis',
            name='risk_analysis',
            field=models.JSONField(default=list, help_text='Lista de análisis de riesgos con relevance y text', verbose_name='Análisis de riesgos'),
        ),
    ]
