# Generated by Django 5.2.3 on 2025-12-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_alter_mitigationactionevidence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntaryhazardreport',
            options={'verbose_name': 'VHR', 'verbose_name_plural': 'VHR'},
        ),
        migrations.RemoveField(
            model_name='voluntaryhazardreport',
            name='is_registered',
        ),
    ]
