# Generated by Django 5.2.3 on 2025-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_alter_voluntaryhazardreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntaryhazardreport',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Registrado'),
        ),
    ]
