# Generated by Django 5.2.3 on 2025-10-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_alter_reportanalysis_recommendations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('OVERDUE', 'Vencida')], default='PENDING', max_length=20, verbose_name='Estatus')),
                ('due_date', models.DateField(blank=True, default=None, null=True, verbose_name='Vencimiento')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.reportanalysis', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Acción de SMS',
                'verbose_name_plural': 'Acciones de SMS',
            },
        ),
    ]
