# Generated by Django 5.2.3 on 2025-10-16 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_smsaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaction',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 16, 18, 51, 0, 739944, tzinfo=datetime.timezone.utc), null=True, verbose_name='Vencimiento'),
        ),
    ]
