# Generated by Django 5.2.3 on 2025-12-09 14:02

import django.db.models.deletion
import sms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_voluntaryhazardreport_is_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntaryhazardreport',
            options={'verbose_name': 'RVP', 'verbose_name_plural': 'RVP'},
        ),
        migrations.RemoveField(
            model_name='mitigationactionevidence',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='mitigationactionevidence',
            name='responsible',
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='due_date',
            field=models.DateField(default=sms.models.default_due_date, verbose_name='Fecha límite'),
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='responsible',
            field=models.ForeignKey(help_text='Solo usuarios con rol de Staff o Instructor pueden ser asignados como responsables', limit_choices_to=models.Q(('role', 'STAFF'), ('role', 'INSTRUCTOR'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for_mitigation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
