# Generated by Django 5.2.3 on 2025-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_alter_voluntaryhazardreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigationactionevidence',
            name='status',
        ),
        migrations.AlterField(
            model_name='mitigationaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=9, verbose_name='Estatus'),
        ),
    ]
