# Generated by Django 5.2.3 on 2025-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_alter_smsaction_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento'),
        ),
    ]
