# Generated by Django 5.2.3 on 2025-12-09 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_remove_mitigationactionevidence_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigationaction',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Solo usuarios con rol de Staff o Instructor pueden ser asignados como responsables', limit_choices_to=models.Q(('role', 'STAFF'), ('role', 'INSTRUCTOR'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_for_mitigation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
