# Generated by Django 5.2.3 on 2025-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_alter_smsaction_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportanalysis',
            name='actions_created',
            field=models.BooleanField(default=False, verbose_name='Acciones creadas'),
        ),
    ]
