# Generated by Django 5.2.3 on 2025-11-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0020_reportanalysis_actions_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportanalysis',
            name='probability',
            field=models.CharField(max_length=1, verbose_name='Probabilidad'),
        ),
        migrations.AlterField(
            model_name='reportanalysis',
            name='severity',
            field=models.CharField(max_length=1, verbose_name='Severidad'),
        ),
    ]
