# Generated by Django 5.2.3 on 2025-12-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0020_alter_mitigationaction_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigationactionevidence',
            name='notes',
        ),
    ]
