# Generated by Django 5.2.3 on 2026-01-22 13:43

import sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_remove_mitigationactionevidence_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigationaction',
            name='follow_date',
            field=models.DateField(default=sms.models.default_follow_date, verbose_name='Fecha de seguimiento'),
        ),
    ]
