# Generated by Django 5.2.3 on 2026-01-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_mitigationaction_follow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigationactionevidence',
            name='mitigation_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='sms.mitigationaction', verbose_name='MMR'),
        ),
    ]
