# Generated by Django 5.2.3 on 2026-08-03 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_alter_mitigationactionevidence_mitigation_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('sms_user_fullname', models.CharField(max_length=200, verbose_name='Coordinador de SMS')),
                ('dir_user_fullname', models.CharField(max_length=200, verbose_name='Director')),
                ('hazard_description', models.TextField(max_length=300, verbose_name='Descripción del peligro')),
                ('hazard_source', models.CharField(choices=[('VHR', 'Reporte Voluntario de Peligro'), ('ROS', 'Reporte Obligatorio de Suceso'), ('INT_AUD', 'Auditoría Interna'), ('EXT_AUD', 'Auditoría Externa')], default='VHR', max_length=10, verbose_name='Fuente del peligro')),
                ('hazard_type', models.CharField(choices=[('ENV', 'Ambiental'), ('TEC', 'Técnico'), ('ORG', 'Organizacional'), ('HUM', 'Humano')], max_length=3, verbose_name='Tipo de peligro')),
                ('hazard_area', models.CharField(choices=[('ADMIN', 'Sede administrativa'), ('PLATFORM', 'Plataforma'), ('AIRPORT_OFFICE', 'Ofic. Aeropuerto'), ('OPERATIONS', 'Operaciones'), ('OTHER', 'Otro')], max_length=20, verbose_name='Área del peligro')),
                ('hazard_causes', models.TextField(max_length=1000, verbose_name='Posibles causas')),
                ('defenses', models.TextField(max_length=500, verbose_name='Defensas existentes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_evaluation_report', to='sms.voluntaryhazardreport', verbose_name='Reporte Voluntario de Peligro')),
                ('selected_risk', models.ForeignKey(help_text='Consecuencia seleccionada para evaluar y mitigar en el RER.', on_delete=django.db.models.deletion.RESTRICT, related_name='risk_evaluation_reports', to='sms.risk', verbose_name='Riesgo seleccionado')),
            ],
            options={
                'verbose_name': 'Registro de Evaluación de Riesgos',
                'verbose_name_plural': 'Registros de Evaluación de Riesgos',
            },
        ),
    ]
