# Generated by Django 5.2.3 on 2026-08-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_riskevaluationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskevaluationreport',
            name='selected_risk',
            field=models.ForeignKey(help_text='Peor consecuencia seleccionada para el índice de riesgo inicial.', on_delete=django.db.models.deletion.RESTRICT, related_name='risk_evaluation_reports', to='sms.risk', verbose_name='Riesgo de referencia'),
        ),
    ]
