# Generated by Django 5.2.3 on 2026-08-05 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0025_alter_riskevaluationreport_selected_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevaluationreport',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalización del análisis residual'),
        ),
        migrations.AddField(
            model_name='riskevaluationreport',
            name='analysis_error',
            field=models.TextField(blank=True, verbose_name='Error del análisis residual'),
        ),
        migrations.AddField(
            model_name='riskevaluationreport',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del análisis residual'),
        ),
        migrations.AddField(
            model_name='riskevaluationreport',
            name='analysis_status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de análisis'), ('PROCESSING', 'Analizando'), ('READY_FOR_REVIEW', 'Listo para revisión'), ('FAILED', 'Error en el análisis'), ('REVIEWED', 'Revisado')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado del análisis residual'),
        ),
        migrations.AddField(
            model_name='riskevaluationreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='riskevaluationreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_risk_evaluation_reports', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.CreateModel(
            name='RiskResidualEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_severity', models.CharField(choices=[('A', 'A - Catastrófico'), ('B', 'B - Peligroso'), ('C', 'C - Grave'), ('D', 'D - Leve'), ('E', 'E - Insignificante')], max_length=1, verbose_name='Severidad residual propuesta')),
                ('proposed_probability', models.CharField(choices=[('1', '1 - Sumamente improbable'), ('2', '2 - Improbable'), ('3', '3 - Remota'), ('4', '4 - Ocasional'), ('5', '5 - Frecuente')], max_length=1, verbose_name='Probabilidad residual propuesta')),
                ('justification', models.TextField(verbose_name='Justificación de SARA')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('rer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residual_evaluations', to='sms.riskevaluationreport', verbose_name='Registro de Evaluación de Riesgos')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_residual_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual_evaluation', to='sms.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo Residual',
                'verbose_name_plural': 'Evaluaciones de Riesgo Residual',
            },
        ),
    ]
