# Generated by Django 5.2.3 on 2026-08-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0026_riskevaluationreport_analysis_completed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskResidualEvaluation',
        ),
    ]
