# Generated by Django 5.0.6 on 2025-03-30 23:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_alter_instructor_instructor_license_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ppa', 'PPA'), ('hvi', 'HVI'), ('pca', 'PCA'), ('tla', 'TLA')], default='ppa', max_length=10, unique=True)),
                ('name', models.CharField(choices=[('private_pilot', 'Piloto Privado'), ('instrument_rating', 'Vuelo Instrumental'), ('commercial_pilot', 'Piloto Comercial'), ('airline_transport_pilot', 'Línea Aérea')], default='private_pilot', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Curso base',
                'verbose_name_plural': 'Cursos base',
            },
        ),
        migrations.CreateModel(
            name='BaseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('passing_grade', models.PositiveIntegerField(default=80, help_text='Nota mínima requerida para aprobar la materia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.basecourse')),
            ],
            options={
                'verbose_name': 'Materia base',
                'verbose_name_plural': 'Materias base',
            },
        ),
        migrations.CreateModel(
            name='CourseEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], max_length=10)),
                ('base_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.basecourse')),
                ('students', models.ManyToManyField(blank=True, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='SubjectEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(12, 30))),
                ('base_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.basesubject')),
                ('instructor', models.ForeignKey(limit_choices_to=models.Q(('instructor_type', 'TIERRA'), ('instructor_type', 'DUAL'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.instructor')),
                ('students', models.ManyToManyField(limit_choices_to={'student_phase': 'TIERRA'}, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
