# Generated by Django 5.0.6 on 2025-04-04 00:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'ordering': ['course_type', 'code'], 'verbose_name': 'Subject Type', 'verbose_name_plural': 'Subject Types'},
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.coursetype', verbose_name='Tipo de Curso'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='recovery_passing_grade',
            field=models.PositiveIntegerField(default=90, help_text='Nota mínima requerida para aprobar la materia en reparación', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
