# Generated by Django 5.0.6 on 2025-03-30 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseedition',
            old_name='base_course',
            new_name='course_type',
        ),
        migrations.RenameModel(
            old_name='BaseCourse',
            new_name='CourseType',
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('passing_grade', models.PositiveIntegerField(default=80, help_text='Nota mínima requerida para aprobar la materia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.coursetype')),
            ],
            options={
                'verbose_name': 'Materia base',
                'verbose_name_plural': 'Materias base',
            },
        ),
        migrations.AddField(
            model_name='subjectedition',
            name='subject_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.subjecttype'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='base_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_editions', to='academic.subjecttype'),
        ),
        migrations.DeleteModel(
            name='BaseSubject',
        ),
    ]
