# Generated by Django 5.0.6 on 2025-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_base_course_courseedition_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='time_slot',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('Piloto Privado', 'Piloto Privado'), ('Vuelo Instrumental', 'Vuelo Instrumental'), ('Piloto Comercial', 'Piloto Comercial'), ('Línea Aérea', 'Línea Aérea')], default='private_pilot', max_length=100, unique=True),
        ),
    ]
