# Generated by Django 5.0.6 on 2025-04-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_subjecttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseedition',
            options={'ordering': ['course_type', 'edition'], 'verbose_name': 'Course Edition', 'verbose_name_plural': 'Course Editions'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['code'], 'verbose_name': 'Course Type', 'verbose_name_plural': 'Course Types'},
        ),
        migrations.AlterModelOptions(
            name='subjectedition',
            options={'ordering': ['course_edition', 'subject_type'], 'verbose_name': 'Subject Edition', 'verbose_name_plural': 'Subject Editions'},
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='time_slot',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='time_slot',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=10),
        ),
    ]
