# Generated by Django 5.0.6 on 2025-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_courseedition_time_slot_alter_coursetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('Piloto Privado', 'Piloto Privado'), ('Vuelo Instrumental', 'Vuelo Instrumental'), ('Piloto Comercial', 'Piloto Comercial'), ('Línea Aérea', 'Línea Aérea')], default='Piloto Privado', max_length=100, unique=True),
        ),
    ]
