# Generated by Django 5.0.6 on 2025-04-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_courseedition_options_alter_coursetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseedition',
            name='end_date',
        ),
    ]
