# Generated by Django 5.0.6 on 2025-03-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_coursetype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseedition',
            options={'verbose_name': 'Course Edition', 'verbose_name_plural': 'Course Editions'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'verbose_name': 'Course Type', 'verbose_name_plural': 'Course Types'},
        ),
        migrations.AlterModelOptions(
            name='subjectedition',
            options={'verbose_name': 'Subject Edition', 'verbose_name_plural': 'Subject Editions'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': 'Base Subject', 'verbose_name_plural': 'Base Subjects'},
        ),
    ]
