# Generated by Django 5.0.6 on 2025-04-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_subjectedition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseedition',
            options={'ordering': ['course_type', 'edition'], 'verbose_name': 'Edición de Curso', 'verbose_name_plural': 'Ediciones de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['code'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='subjectedition',
            options={'ordering': ['subject_type'], 'verbose_name': 'Edición de Materia', 'verbose_name_plural': 'Ediciones de Materias'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'ordering': ['course_type', 'code'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
    ]
