# Generated by Django 5.0.6 on 2025-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_courseedition_options_alter_coursetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='time_slot',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='ppa', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='time_slot',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10),
        ),
    ]
