# Generated by Django 5.0.6 on 2025-05-23 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_courseedition_options_alter_coursetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectedition',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota')),
                ('test_type', models.CharField(choices=[('STANDARD', 'Examen estándar'), ('RECOVERY', 'Examen de reparación')], default='STANDARD', max_length=10, verbose_name='Tipo de Examen')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('subject_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.subjectedition', verbose_name='Edición de Materia')),
            ],
            options={
                'verbose_name': 'Nota de Estudiante',
                'verbose_name_plural': 'Notas de Estudiantes',
                'ordering': ['-date'],
                'unique_together': {('subject_edition', 'student', 'test_type')},
            },
        ),
    ]
