# Generated by Django 5.0.6 on 2025-03-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_courseedition_time_slot_alter_coursetype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='course_type',
            field=models.ForeignKey(default='Piloto Privado', on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.coursetype'),
        ),
    ]
