# Generated by Django 5.0.6 on 2025-03-31 18:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_courseedition_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.coursetype'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='PPA', max_length=10, unique=True),
        ),
    ]
