# Generated by Django 5.0.6 on 2025-05-30 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_subjectedition_students_studentgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(fields=('subject_edition', 'student', 'test_type'), name='unique_student_grade', violation_error_message='Ya existe una nota para este estudiante en esta materia con el mismo tipo de examen.'),
        ),
    ]
