# Generated by Django 5.0.6 on 2025-05-30 15:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_studentgrade_unique_student_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgrade',
            name='unique_student_grade',
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 30), verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='instructor',
            field=models.ForeignKey(limit_choices_to=models.Q(('instructor_profile__instructor_type', 'TIERRA'), ('instructor_profile__instructor_type', 'DUAL'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='subject_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.subjecttype', verbose_name='Tipo de Materia'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='time_slot',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=10, verbose_name='Horario'),
        ),
    ]
