# Generated by Django 5.0.6 on 2025-03-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_courseedition_course_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': 'Subject Type', 'verbose_name_plural': 'Subject Types'},
        ),
    ]
