# Generated by Django 5.0.6 on 2025-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_studentgrade_unique_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='test_type',
            field=models.CharField(choices=[('STANDARD', 'Estándar'), ('RECOVERY', 'Reparación')], default='STANDARD', max_length=10, verbose_name='Tipo de Examen'),
        ),
    ]
