# Generated by Django 5.0.6 on 2025-06-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_studentgrade_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='submitted_by',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_grades', to=settings.AUTH_USER_MODEL, verbose_name='Instructor que registró la nota'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('subject_edition', 'student', 'test_type')},
        ),
    ]
