# Generated by Django 5.0.6 on 2025-03-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_coursetype_credit_hours_alter_coursetype_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseedition',
            unique_together={('course_type', 'edition')},
        ),
    ]
