# Generated by Django 5.0.6 on 2025-06-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_studentgrade_submitted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='submitted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_grades', to=settings.AUTH_USER_MODEL, verbose_name='Instructor que registró la nota'),
        ),
    ]
