# Generated by Django 5.0.6 on 2025-03-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_courseedition_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectedition',
            name='base_subject',
        ),
    ]
