# Generated by Django 5.0.6 on 2025-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_remove_subjectedition_base_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='PPA', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('Piloto Privado Avión', 'Piloto Privado Avión'), ('Habilitación Vuelo Instrumental Avión', 'Habilitación Vuelo Instrumental Avión'), ('Piloto Comercial Avión', 'Piloto Comercial Avión'), ('Instructor de Vuelo Avión', 'Instructor de Vuelo Avión'), ('Instructor de Vuelo Simulado', 'Instructor de Vuelo Simulado'), ('Despachador de Vuelo', 'Despachador de Vuelo')], default='Piloto Privado', max_length=100, unique=True),
        ),
    ]
