# Generated by Django 5.0.6 on 2025-06-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_studentgrade_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='submitted_by_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Instructor que registró la nota'),
        ),
    ]
