# Generated by Django 5.0.6 on 2025-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_coursetype_code_alter_coursetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttype',
            name='code',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA-AER-I'), ('PPA-SYE-I', 'PPA-SYE-I'), ('PPA-MET-I', 'PPA-MET-I'), ('PPA-DER-I', 'PPA-DER-I'), ('PPA-NAV', 'PPA-NAV'), ('PPA-UDM', 'PPA-UDM'), ('PPA-MYC', 'PPA-MYC'), ('PPA-PRF', 'PPA-PRF'), ('PPA-RDC', 'PPA-RDC'), ('PPA-FHH', 'PPA-FHH'), ('PPA-SEG', 'PPA-SEG'), ('PPA-SPV', 'PPA-SPV'), ('PPA-PRO-I', 'PPA-PRO-I'), ('HVI-DER', 'HVI-DER'), ('HVI-SYE', 'HVI-SYE'), ('HVI-PPV', 'HVI-PPV'), ('HVI-MET', 'HVI-MET'), ('HVI-RDN', 'HVI-RDN'), ('HVI-PRO', 'HVI-PRO'), ('HVI-CAR', 'HVI-CAR'), ('PCA-AER-II', 'PCA-AER-II'), ('PCA-SYE-II', 'PCA-SYE-II'), ('PCA-MET-II', 'PCA-MET-II'), ('PCA-DER-II', 'PCA-DER-II'), ('PCA-FHH-II', 'PCA-FHH-II'), ('PCA-INST-II', 'PCA-INST-II'), ('PCA-RDN', 'PCA-RDN'), ('PCA-PRO-II', 'PCA-PRO-II'), ('PCA-SEG-II', 'PCA-SEG-II'), ('IVA-PFD', 'IVA-PFD'), ('IVA-ADE', 'IVA-ADE'), ('IVS-PFD', 'IVS-PFD'), ('IVS-ADE', 'IVS-ADE'), ('DDV-DER', 'DDV-DER'), ('DDV-ADA', 'DDV-ADA'), ('DDV-MYP', 'DDV-MYP'), ('DDV-NAV', 'DDV-NAV'), ('DDV-CTA', 'DDV-CTA'), ('DDV-MET', 'DDV-MET'), ('DDV-CMC', 'DDV-CMC'), ('DDV-TMP', 'DDV-TMP'), ('DDV-PDV', 'DDV-PDV'), ('DDV-MDV', 'DDV-MDV'), ('DDV-RDC', 'DDV-RDC'), ('DDV-FHH', 'DDV-FHH'), ('DDV-SEG', 'DDV-SEG')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(choices=[('PPA-AER-I', 'Aerodinámica I'), ('PPA-SYE-I', 'Sistemas y Equipos I'), ('PPA-MET-I', 'Meteorología I'), ('PPA-DER-I', 'Derecho Aeronáutico I'), ('PPA-NAV', 'Navegación Visual'), ('PPA-UDM', 'Unidades de Medida'), ('PPA-MYC', 'Masa y Centrado'), ('PPA-PRF', 'Performance'), ('PPA-RDC', 'Radiocomunicaciones'), ('PPA-FHH', 'Factores Humanos'), ('PPA-SEG', 'Seguridad Aérea'), ('PPA-SPV', 'Supervivencia'), ('PPA-PRO-I', 'Procedimientos Operacionales I'), ('HVI-DER', 'Derecho Aeronáutico'), ('HVI-SYE', 'Sistemas y Equipos'), ('HVI-PPV', 'Performance y Planificación de Vuelo'), ('HVI-MET', 'Meteorología'), ('HVI-RDN', 'Radionavegación'), ('HVI-PRO', 'Procedimientos Operacionales'), ('HVI-CAR', 'Comunicaciones Aeronáuticas'), ('PCA-AER-II', 'Aerodinámica II'), ('PCA-SYE-II', 'Sistemas y Equipos II'), ('PCA-MET-II', 'Meteorología II'), ('PCA-DER-II', 'Derecho Aeronáutico II'), ('PCA-FHH-II', 'Factores Humanos II'), ('PCA-INST-II', 'Instrumentos II'), ('PCA-RDN', 'Radionavegación'), ('PCA-PRO-II', 'Procedimientos Operacionales II'), ('PCA-SEG-II', 'Seguridad Aérea II'), ('IVA-PFD', 'Peligros Durante la Simulación de Fallas'), ('IVA-ADE', 'Administración de la Enseñanza'), ('IVS-PFD', 'Peligros Durante la Simulación de Fallas'), ('IVS-ADE', 'Administración de la Enseñanza'), ('DDV-DER', 'Derecho Aeronáutico'), ('DDV-ADA', 'Adoctrinamiento en Aviación'), ('DDV-MYP', 'Masa y Performance de la Aeronave'), ('DDV-NAV', 'Navegación'), ('DDV-CTA', 'Control de Tránsito Aéreo'), ('DDV-MET', 'Meteorología'), ('DDV-CMC', 'Control de Masa y Centrado'), ('DDV-TMP', 'Transporte de Mercancías Peligrosas'), ('DDV-PDV', 'Planificación de Vuelo'), ('DDV-MDV', 'Monitoreo del Vuelo'), ('DDV-RDC', 'Radiocomunicaciones'), ('DDV-FHH', 'Factores Humanos'), ('DDV-SEG', 'Seguridad')], max_length=100, unique=True),
        ),
    ]
