# Generated by Django 5.0.6 on 2025-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_studentgrade_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='submitted_by_username',
            field=models.CharField(default='-', max_length=150, verbose_name='Registrado por'),
        ),
    ]
