# Generated by Django 5.0.6 on 2025-04-01 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_alter_subjecttype_code_alter_subjecttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttype',
            name='recovery_passing_grade',
            field=models.PositiveIntegerField(default=90, help_text='Nota mínima requerida para aprobar la materia en reparación', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='credit_hours',
            field=models.PositiveIntegerField(default=0, help_text='Horas académicas de la materia'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA - Aerodinámica I'), ('PPA-SYE-I', 'PPA - Sistemas y Equipos I'), ('PPA-MET-I', 'PPA - Meteorología I'), ('PPA-DER-I', 'PPA - Derecho Aeronáutico I'), ('PPA-NAV', 'PPA - Navegación Visual'), ('PPA-UDM', 'PPA - Unidades de Medida'), ('PPA-MYC', 'PPA - Masa y Centrado'), ('PPA-PRF', 'PPA - Performance'), ('PPA-RDC', 'PPA - Radiocomunicaciones'), ('PPA-FHH', 'PPA - Factores Humanos'), ('PPA-SEG', 'PPA - Seguridad Aérea'), ('PPA-SPV', 'PPA - Supervivencia'), ('PPA-PRO-I', 'PPA - Procedimientos Operacionales I'), ('HVI-DER', 'HVI - Derecho Aeronáutico'), ('HVI-SYE', 'HVI - Sistemas y Equipos'), ('HVI-PPV', 'HVI - Performance y Planificación de Vuelo'), ('HVI-MET', 'HVI - Meteorología'), ('HVI-RDN', 'HVI - Radionavegación'), ('HVI-PRO', 'HVI - Procedimientos Operacionales'), ('HVI-CAR', 'HVI - Comunicaciones Aeronáuticas'), ('PCA-AER-II', 'PCA - Aerodinámica II'), ('PCA-SYE-II', 'PCA - Sistemas y Equipos II'), ('PCA-MET-II', 'PCA - Meteorología II'), ('PCA-DER-II', 'PCA - Derecho Aeronáutico II'), ('PCA-FHH-II', 'PCA - Factores Humanos II'), ('PCA-INST-II', 'PCA - Instrumentos II'), ('PCA-RDN', 'PCA - Radionavegación'), ('PCA-PRO-II', 'PCA - Procedimientos Operacionales II'), ('PCA-SEG-II', 'PCA - Seguridad Aérea II'), ('IVA-PFD', 'IVA - Peligros Durante la Simulación de Fallas'), ('IVA-ADE', 'IVA - Administración de la Enseñanza'), ('IVS-PFD', 'IVS - Peligros Durante la Simulación de Fallas'), ('IVS-ADE', 'IVS - Administración de la Enseñanza'), ('DDV-DER', 'DDV - Derecho Aeronáutico'), ('DDV-ADA', 'DDV - Adoctrinamiento en Aviación'), ('DDV-MYP', 'DDV - Masa y Performance de la Aeronave'), ('DDV-NAV', 'DDV - Navegación'), ('DDV-CTA', 'DDV - Control de Tránsito Aéreo'), ('DDV-MET', 'DDV - Meteorología'), ('DDV-CMC', 'DDV - Control de Masa y Centrado'), ('DDV-TMP', 'DDV - Transporte de Mercancías Peligrosas'), ('DDV-PDV', 'DDV - Planificación de Vuelo'), ('DDV-MDV', 'DDV - Monitoreo del Vuelo'), ('DDV-RDC', 'DDV - Radiocomunicaciones'), ('DDV-FHH', 'DDV - Factores Humanos'), ('DDV-SEG', 'DDV - Seguridad')], max_length=100, unique=True),
        ),
    ]
