# Generated by Django 5.0.6 on 2025-06-04 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_studentgrade_student_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_grades', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='student_username',
            field=models.CharField(default='-', editable=False, max_length=150, verbose_name='Usuario'),
        ),
    ]
