# Generated by Django 5.2.3 on 2025-06-17 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_alter_studentgrade_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(fields=('subject_edition', 'student', 'test_type'), name='unique_student_grade', violation_error_message='Ya existe una nota para este estudiante con el mismo tipo de examen'),
        ),
    ]
