# Generated by Django 5.2.3 on 2025-07-15 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_alter_studentgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgrade',
            name='unique_student_grade',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student_username',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='submitted_by_username',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='instructor_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='instructor_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID instructor'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='instructor_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID alumno'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(fields=('subject_edition', 'student_id', 'test_type'), name='unique_student_grade', violation_error_message='Ya existe una nota para este estudiante con el mismo tipo de examen'),
        ),
    ]
