# Generated by Django 5.2.3 on 2025-07-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_remove_studentgrade_unique_student_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='instructor',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('instructor_profile__instructor_type', 'TIERRA'), ('instructor_profile__instructor_type', 'DUAL'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='submitted_grades', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
