# Generated by Django 5.2.3 on 2025-07-21 19:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_alter_coursetype_code_alter_coursetype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseedition',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='academic.coursetype', verbose_name='Tipo de Curso'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='time_slot',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=10, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(choices=[('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PPA-T', max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='credit_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas académicas'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('Piloto Privado Avión Teórico', 'Piloto Privado Avión Teórico'), ('Piloto Privado Avión Práctico', 'Piloto Privado Avión Práctico'), ('Habilitación Vuelo Instrumental Avión Teórico', 'Habilitación Vuelo Instrumental Avión Teórico'), ('Habilitación Vuelo Instrumental Avión Práctico', 'Habilitación Vuelo Instrumental Avión Práctico'), ('Piloto Comercial Avión Teórico', 'Piloto Comercial Avión Teórico'), ('Piloto Comercial Avión Práctico', 'Piloto Comercial Avión Práctico'), ('Instructor de Vuelo Avión Teórico', 'Instructor de Vuelo Avión Teórico'), ('Instructor de Vuelo Avión Práctico', 'Instructor de Vuelo Avión Práctico'), ('Instructor de Vuelo Simulado Teórico', 'Instructor de Vuelo Simulado Teórico'), ('Instructor de Vuelo Simulado Práctico', 'Instructor de Vuelo Simulado Práctico'), ('Recalificación', 'Recalificación')], default='Piloto Privado Avión Teórico', max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='code',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA-AER-I'), ('PPA-SYE-I', 'PPA-SYE-I'), ('PPA-MET-I', 'PPA-MET-I'), ('PPA-DER-I', 'PPA-DER-I'), ('PPA-NAV', 'PPA-NAV'), ('PPA-UDM', 'PPA-UDM'), ('PPA-MYC', 'PPA-MYC'), ('PPA-PRF', 'PPA-PRF'), ('PPA-RDC', 'PPA-RDC'), ('PPA-FHH', 'PPA-FHH'), ('PPA-SEG', 'PPA-SEG'), ('PPA-SPV', 'PPA-SPV'), ('PPA-PRO-I', 'PPA-PRO-I'), ('HVI-DER', 'HVI-DER'), ('HVI-SYE', 'HVI-SYE'), ('HVI-PPV', 'HVI-PPV'), ('HVI-MET', 'HVI-MET'), ('HVI-RDN', 'HVI-RDN'), ('HVI-PRO', 'HVI-PRO'), ('HVI-CAR', 'HVI-CAR'), ('PCA-AER-II', 'PCA-AER-II'), ('PCA-SYE-II', 'PCA-SYE-II'), ('PCA-MET-II', 'PCA-MET-II'), ('PCA-DER-II', 'PCA-DER-II'), ('PCA-FHH-II', 'PCA-FHH-II'), ('PCA-INST-II', 'PCA-INST-II'), ('PCA-RDN', 'PCA-RDN'), ('PCA-PRO-II', 'PCA-PRO-II'), ('PCA-SEG-II', 'PCA-SEG-II'), ('IVA-PFD', 'IVA-PFD'), ('IVA-ADE', 'IVA-ADE'), ('IVS-PFD', 'IVS-PFD'), ('IVS-ADE', 'IVS-ADE')], max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='credit_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas académicas'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA - Aeronáutica I'), ('PPA-SYE-I', 'PPA - Sistemas y Equipos I'), ('PPA-MET-I', 'PPA - Meteorología I'), ('PPA-DER-I', 'PPA - Derecho Aeronáutico I'), ('PPA-NAV', 'PPA - Navegación Visual'), ('PPA-UDM', 'PPA - Unidades de Medida'), ('PPA-MYC', 'PPA - Masa y Centrado'), ('PPA-PRF', 'PPA - Performance'), ('PPA-RDC', 'PPA - Radiocomunicaciones'), ('PPA-FHH', 'PPA - Factores Humanos'), ('PPA-SEG', 'PPA - Seguridad Aérea'), ('PPA-SPV', 'PPA - Supervivencia'), ('PPA-PRO-I', 'PPA - Procedimientos Operacionales I'), ('HVI-DER', 'HVI - Derecho Aeronáutico'), ('HVI-SYE', 'HVI - Sistemas y Equipos'), ('HVI-PPV', 'HVI - Performance y Planificación de Vuelo'), ('HVI-MET', 'HVI - Meteorología'), ('HVI-RDN', 'HVI - Radionavegación'), ('HVI-PRO', 'HVI - Procedimientos Operacionales'), ('HVI-CAR', 'HVI - Comunicaciones Aeronáuticas'), ('PCA-AER-II', 'PCA - Aerodinámica II'), ('PCA-SYE-II', 'PCA - Sistemas y Equipos II'), ('PCA-MET-II', 'PCA - Meteorología II'), ('PCA-DER-II', 'PCA - Derecho Aeronáutico II'), ('PCA-FHH-II', 'PCA - Factores Humanos II'), ('PCA-INST-II', 'PCA - Instrumentos II'), ('PCA-RDN', 'PCA - Radionavegación'), ('PCA-PRO-II', 'PCA - Procedimientos Operacionales II'), ('PCA-SEG-II', 'PCA - Seguridad Aérea II'), ('IVA-PFD', 'IVA - Peligros Durante la Simulación de Fallas'), ('IVA-ADE', 'IVA - Administración de la Enseñanza'), ('IVS-PFD', 'IVS - Peligros Durante la Simulación de Fallas'), ('IVS-ADE', 'IVS - Administración de la Enseñanza')], max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='passing_grade',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota mínima requerida para aprobar'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='recovery_passing_grade',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota mínima requerida para aprobar la reparación'),
        ),
    ]
