# Generated by Django 5.2.3 on 2025-07-21 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_courseedition_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseedition',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
    ]
