# Generated by Django 5.2.3 on 2025-07-21 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_remove_courseedition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='edition',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edición'),
        ),
    ]
