# Generated by Django 5.2.3 on 2025-07-21 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_alter_courseedition_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='edition',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='courseedition',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=10, null=True, verbose_name='Horario'),
        ),
    ]
