# Generated by Django 5.2.3 on 2026-01-28 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_standardize_permission_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseedition',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('student_profile__isnull', False)), related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
