# Generated by Django 5.2.3 on 2026-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_alter_subjectedition_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseedition',
            name='modality',
            field=models.CharField(choices=[('GROUP', 'Grupal'), ('INDIVIDUAL', 'Individual')], default='GROUP', max_length=10, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='code',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA-AER-I'), ('PPA-SYE-I', 'PPA-SYE-I'), ('PPA-MET-I', 'PPA-MET-I'), ('PPA-DER-I', 'PPA-DER-I'), ('PPA-NAV', 'PPA-NAV'), ('PPA-UDM', 'PPA-UDM'), ('PPA-MYC', 'PPA-MYC'), ('PPA-PRF', 'PPA-PRF'), ('PPA-RDC', 'PPA-RDC'), ('PPA-FH-I', 'PPA-FH-I'), ('PPA-SEG-I', 'PPA-SEG-I'), ('PPA-SPV', 'PPA-SPV'), ('PPA-PRO-I', 'PPA-PRO-I'), ('HVI-DER', 'HVI-DER'), ('HVI-SYE', 'HVI-SYE'), ('HVI-PPV', 'HVI-PPV'), ('HVI-MET', 'HVI-MET'), ('HVI-RDN', 'HVI-RDN'), ('HVI-PRO', 'HVI-PRO'), ('HVI-CAR', 'HVI-CAR'), ('PCA-AER-II', 'PCA-AER-II'), ('PCA-SYE-II', 'PCA-SYE-II'), ('PCA-MET-II', 'PCA-MET-II'), ('PCA-DER-II', 'PCA-DER-II'), ('PCA-FHH-II', 'PCA-FHH-II'), ('PCA-INST-II', 'PCA-INST-II'), ('PCA-RDN', 'PCA-RDN'), ('PCA-PRO-II', 'PCA-PRO-II'), ('PCA-SEG-II', 'PCA-SEG-II'), ('IVA-PFD', 'IVA-PFD'), ('IVA-ADE', 'IVA-ADE'), ('IVS-PFD', 'IVS-PFD'), ('IVS-ADE', 'IVS-ADE')], max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(choices=[('PPA-AER-I', 'PPA - Aeronáutica I'), ('PPA-SYE-I', 'PPA - Sistemas y Equipos I'), ('PPA-MET-I', 'PPA - Meteorología I'), ('PPA-DER-I', 'PPA - Derecho Aeronáutico I'), ('PPA-NAV', 'PPA - Navegación Visual'), ('PPA-UDM', 'PPA - Unidades de Medida'), ('PPA-MYC', 'PPA - Masa y Centrado'), ('PPA-PRF', 'PPA - Performance'), ('PPA-RDC', 'PPA - Radiocomunicaciones'), ('PPA-FH-I', 'PPA - Factores Humanos I'), ('PPA-SEG-I', 'PPA - Seguridad Aérea I'), ('PPA-SPV', 'PPA - Supervivencia'), ('PPA-PRO-I', 'PPA - Procedimientos Operacionales I'), ('HVI-DER', 'HVI - Derecho Aeronáutico'), ('HVI-SYE', 'HVI - Sistemas y Equipos'), ('HVI-PPV', 'HVI - Performance y Planificación de Vuelo'), ('HVI-MET', 'HVI - Meteorología'), ('HVI-RDN', 'HVI - Radionavegación'), ('HVI-PRO', 'HVI - Procedimientos Operacionales'), ('HVI-CAR', 'HVI - Comunicaciones Aeronáuticas'), ('PCA-AER-II', 'PCA - Aerodinámica II'), ('PCA-SYE-II', 'PCA - Sistemas y Equipos II'), ('PCA-MET-II', 'PCA - Meteorología II'), ('PCA-DER-II', 'PCA - Derecho Aeronáutico II'), ('PCA-FHH-II', 'PCA - Factores Humanos II'), ('PCA-INST-II', 'PCA - Instrumentos II'), ('PCA-RDN', 'PCA - Radionavegación'), ('PCA-PRO-II', 'PCA - Procedimientos Operacionales II'), ('PCA-SEG-II', 'PCA - Seguridad Aérea II'), ('IVA-PFD', 'IVA - Peligros Durante la Simulación de Fallas'), ('IVA-ADE', 'IVA - Administración de la Enseñanza'), ('IVS-PFD', 'IVS - Peligros Durante la Simulación de Fallas'), ('IVS-ADE', 'IVS - Administración de la Enseñanza')], max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
