# Generated by Django 5.2.3 on 2026-02-24 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_courseedition_modality_alter_subjecttype_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseedition',
            options={'ordering': ['course_type', 'modality', 'edition'], 'verbose_name': 'Edición de Curso', 'verbose_name_plural': 'Ediciones de Cursos'},
        ),
        migrations.AlterUniqueTogether(
            name='courseedition',
            unique_together={('course_type', 'modality', 'edition')},
        ),
        migrations.AddField(
            model_name='courseedition',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2026)], verbose_name='Año del curso'),
        ),
    ]
