# Generated by Django 5.2.3 on 2026-04-21 22:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def backfill_grading_components(apps, schema_editor):
    SubjectEdition = apps.get_model('academic', 'SubjectEdition')
    Component = apps.get_model('academic', 'SubjectEditionGradingComponent')
    StudentGrade = apps.get_model('academic', 'StudentGrade')
    for se in SubjectEdition.objects.all():
        comp, _ = Component.objects.get_or_create(
            subject_edition_id=se.pk,
            code='theory',
            defaults={
                'kind': 'THEORY',
                'label': 'Examen teórico',
                'weight': Decimal('1.0'),
                'order': 0,
            },
        )
        StudentGrade.objects.filter(subject_edition_id=se.pk, component__isnull=True).update(
            component_id=comp.pk
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_alter_courseedition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEditionGradingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador estable, ej. theory, practical', max_length=32, verbose_name='Código')),
                ('kind', models.CharField(choices=[('THEORY', 'Teórico'), ('PRACTICAL', 'Práctico'), ('OTHER', 'Otro')], default='THEORY', max_length=20, verbose_name='Tipo')),
                ('label', models.CharField(help_text='Texto mostrado en informes y administración', max_length=100, verbose_name='Etiqueta')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Fracción del total (los pesos de la edición deben sumar 1.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Peso')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('subject_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_components', to='academic.subjectedition', verbose_name='Edición de materia')),
            ],
            options={
                'verbose_name': 'Componente de calificación',
                'verbose_name_plural': 'Componentes de calificación',
                'ordering': ['subject_edition_id', 'order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjecteditiongradingcomponent',
            constraint=models.UniqueConstraint(fields=('subject_edition', 'code'), name='unique_grading_component_code_per_edition'),
        ),
        migrations.RemoveConstraint(
            model_name='studentgrade',
            name='unique_student_grade',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.subjecteditiongradingcomponent', verbose_name='Componente'),
        ),
        migrations.RunPython(backfill_grading_components, noop_reverse),
        migrations.AlterField(
            model_name='studentgrade',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.subjecteditiongradingcomponent', verbose_name='Componente'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'subject_edition'], name='academic_st_student_3d7ffd_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(
                fields=('component', 'student', 'test_type'),
                name='unique_student_grade_per_component_test_type',
                violation_error_message='Ya existe una nota para este estudiante, componente y tipo de examen',
            ),
        ),
    ]
