# Generated by Django 5.2.3 on 2026-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_grading_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(choices=[('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL'), ('PPA-REC', 'PPA-REC'), ('HVI-REC', 'HVI-REC')], default='PPA-T', max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('Piloto Privado Avión Teórico', 'Piloto Privado Avión Teórico'), ('Piloto Privado Avión Práctico', 'Piloto Privado Avión Práctico'), ('Habilitación Vuelo Instrumental Avión Teórico', 'Habilitación Vuelo Instrumental Avión Teórico'), ('Habilitación Vuelo Instrumental Avión Práctico', 'Habilitación Vuelo Instrumental Avión Práctico'), ('Piloto Comercial Avión Teórico', 'Piloto Comercial Avión Teórico'), ('Piloto Comercial Avión Práctico', 'Piloto Comercial Avión Práctico'), ('Instructor de Vuelo Avión Teórico', 'Instructor de Vuelo Avión Teórico'), ('Instructor de Vuelo Avión Práctico', 'Instructor de Vuelo Avión Práctico'), ('Instructor de Vuelo Simulado Teórico', 'Instructor de Vuelo Simulado Teórico'), ('Instructor de Vuelo Simulado Práctico', 'Instructor de Vuelo Simulado Práctico'), ('Recalificación', 'Recalificación'), ('Piloto Privado Avión Recurrente', 'Piloto Privado Avión Recurrente'), ('Habilitación Vuelo Instrumental Avión Recurrente', 'Habilitación Vuelo Instrumental Avión Recurrente')], default='Piloto Privado Avión Teórico', max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
