# Generated by Django 5.2.3

import django.core.validators
from decimal import Decimal

from django.db import migrations, models


def normalize_theory_practical(apps, schema_editor):
    Component = apps.get_model('academic', 'SubjectEditionGradingComponent')
    StudentGrade = apps.get_model('academic', 'StudentGrade')
    SubjectEdition = apps.get_model('academic', 'SubjectEdition')

    def collapse_kind(se_id, kind_val, target_code):
        rows = list(Component.objects.filter(subject_edition_id=se_id, kind=kind_val))
        if not rows:
            return
        prefer = [r for r in rows if r.code == target_code]
        keeper = min(prefer, key=lambda x: x.pk) if prefer else min(rows, key=lambda x: x.pk)
        for r in rows:
            if r.pk != keeper.pk:
                StudentGrade.objects.filter(component_id=r.pk).update(component_id=keeper.pk)
                r.delete()
        keeper = Component.objects.get(pk=keeper.pk)
        keeper.code = target_code
        keeper.kind = kind_val
        keeper.save(update_fields=['code', 'kind'])

    for se in SubjectEdition.objects.all():
        collapse_kind(se.pk, 'THEORY', 'theory')
        collapse_kind(se.pk, 'PRACTICAL', 'practical')

        while Component.objects.filter(subject_edition_id=se.pk, kind='OTHER').exists():
            o = Component.objects.filter(subject_edition_id=se.pk, kind='OTHER').first()
            theory = Component.objects.filter(subject_edition_id=se.pk, code='theory').first()
            if theory:
                StudentGrade.objects.filter(component_id=o.pk).update(component_id=theory.pk)
                o.delete()
            else:
                o.kind = 'THEORY'
                o.code = 'theory'
                o.save(update_fields=['kind', 'code'])
                collapse_kind(se.pk, 'THEORY', 'theory')

        if not Component.objects.filter(subject_edition_id=se.pk, code='theory').exists():
            Component.objects.create(
                subject_edition_id=se.pk,
                code='theory',
                kind='THEORY',
                label='Examen teórico',
                weight=Decimal('1.0'),
                order=0,
            )
        if not Component.objects.filter(subject_edition_id=se.pk, code='practical').exists():
            Component.objects.create(
                subject_edition_id=se.pk,
                code='practical',
                kind='PRACTICAL',
                label='Evaluación práctica',
                weight=Decimal('0'),
                order=1,
            )

        theory = Component.objects.get(subject_edition_id=se.pk, code='theory')
        pract = Component.objects.get(subject_edition_id=se.pk, code='practical')
        for o in list(Component.objects.filter(subject_edition_id=se.pk).exclude(pk__in=[theory.pk, pract.pk])):
            tgt = pract if o.kind == 'PRACTICAL' else theory
            StudentGrade.objects.filter(component_id=o.pk).update(component_id=tgt.pk)
            o.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0033_alter_coursetype_code_alter_coursetype_name'),
    ]

    operations = [
        migrations.RunPython(normalize_theory_practical, noop_reverse),
        migrations.AlterField(
            model_name='subjecteditiongradingcomponent',
            name='kind',
            field=models.CharField(
                choices=[('THEORY', 'Teórico'), ('PRACTICAL', 'Práctico')],
                default='THEORY',
                max_length=20,
                verbose_name='Tipo',
            ),
        ),
        migrations.AlterField(
            model_name='subjecteditiongradingcomponent',
            name='code',
            field=models.SlugField(
                choices=[('theory', 'Teoría'), ('practical', 'Práctica')],
                help_text='Siempre theory o practical',
                max_length=32,
                verbose_name='Código',
            ),
        ),
        migrations.AlterField(
            model_name='subjecteditiongradingcomponent',
            name='weight',
            field=models.DecimalField(
                decimal_places=3,
                help_text='Fracción del total (teoría + práctica deben sumar 1.0; la práctica puede ser 0)',
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0')),
                    django.core.validators.MaxValueValidator(Decimal('1')),
                ],
                verbose_name='Peso',
            ),
        ),
        migrations.AddConstraint(
            model_name='subjecteditiongradingcomponent',
            constraint=models.UniqueConstraint(
                fields=('subject_edition', 'kind'),
                name='unique_grading_component_kind_per_edition',
            ),
        ),
    ]
