# Generated by Django 5.2.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_theory_practical_grading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttype',
            name='passing_grade',
        ),
        migrations.RemoveField(
            model_name='subjecttype',
            name='recovery_passing_grade',
        ),
    ]
