# Generated by Django 5.2.3 on 2026-04-24 17:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_remove_subjecttype_passing_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecteditiongradingcomponent',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='Solo 1.0 (solo teoría) o, con práctica, 0.8 en teoría y 0.2 en práctica.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Peso'),
        ),
    ]
