# Generated by Django 5.2.3 on 2026-04-25 00:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_edition_weights_char_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectedition',
            name='practical_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Sin práctica: 0. Con práctica: 0.2.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Peso práctica'),
        ),
        migrations.AlterField(
            model_name='subjectedition',
            name='theory_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Solo teoría: 1.0. Con evaluación práctica: 0.8.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Peso teoría'),
        ),
    ]
