# Generated by Django 5.2.3 on 2026-05-15 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_alter_subjectedition_weight_help_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('student_profile__isnull', False)), on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
