# Generated by Django 5.2.3 on 2026-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_alter_studentgrade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
