# Generated by Django 5.2.3 on 2025-09-22 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0007_aircraft_fuel_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la sesión', verbose_name='Fecha')),
                ('block', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='Bloque de la sesión', max_length=1, verbose_name='Bloque')),
                ('status', models.CharField(choices=[('free', 'Libre'), ('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='free', help_text='Estado de la sesión', max_length=10, verbose_name='Estado')),
                ('aircraft', models.ForeignKey(blank=True, help_text='Aeronave de la sesión', limit_choices_to={'is_active': True, 'is_available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_slots', to='fleet.aircraft', verbose_name='Aeronave')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor de la sesión', limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_flight_slots', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
                ('student', models.ForeignKey(blank=True, help_text='Estudiante de la sesión', limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_flight_slots', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Sesión de vuelo',
                'verbose_name_plural': 'Sesiones de vuelo',
                'ordering': ['date', 'block', 'aircraft'],
                'unique_together': {('date', 'block', 'aircraft')},
            },
        ),
    ]
