# Generated by Django 5.2.3 on 2025-09-22 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexible', models.BooleanField(default=False, help_text='Si es selecciona, el estudiante acepta cualquier bloque en esta fecha', verbose_name='Flexible')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de solicitud', verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización', verbose_name='Fecha de actualización')),
                ('notes', models.TextField(blank=True, help_text='Notas de la solicitud', null=True, verbose_name='Notas')),
                ('slot', models.ForeignKey(help_text='Sesión de vuelo de la solicitud', limit_choices_to={'status': 'free'}, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests_slot', to='scheduler.flightslot', verbose_name='Sesión de vuelo')),
                ('student', models.ForeignKey(help_text='Estudiante de la solicitud', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests_student', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de vuelo',
                'verbose_name_plural': 'Solicitudes de vuelo',
                'ordering': ['-requested_at'],
            },
        ),
    ]
