# Generated by Django 5.2.3 on 2025-09-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_flightrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(help_text='Fecha de cierre', verbose_name='Fecha de cierre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización', verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Periodo de entrenamiento',
                'verbose_name_plural': 'Periodos de entrenamiento',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='slot',
            field=models.ForeignKey(help_text='Sesión de vuelo de la solicitud', limit_choices_to={'status': 'free'}, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='scheduler.flightslot', verbose_name='Sesión de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='student',
            field=models.ForeignKey(help_text='Estudiante de la solicitud', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='flightslot',
            name='training_period',
            field=models.ForeignKey(default=None, help_text='Periodo de entrenamiento de la sesión', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.trainingperiod', verbose_name='Periodo de entrenamiento'),
            preserve_default=False,
        ),
    ]
