# Generated by Django 5.2.3 on 2025-09-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_aircraft_fuel_cost'),
        ('scheduler', '0003_trainingperiod_alter_flightrequest_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingperiod',
            name='aircraft',
            field=models.ForeignKey(default=None, help_text='Aeronave', on_delete=django.db.models.deletion.CASCADE, related_name='training_periods', to='fleet.aircraft', verbose_name='Aeronave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingperiod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
