# Generated by Django 5.2.3 on 2025-09-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_trainingperiod_aircraft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='slot',
            field=models.ForeignKey(help_text='Sesión de vuelo de la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='scheduler.flightslot', verbose_name='Sesión de vuelo'),
        ),
        migrations.AlterField(
            model_name='trainingperiod',
            name='end_date',
            field=models.DateField(help_text='Cierre', verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='trainingperiod',
            name='start_date',
            field=models.DateField(help_text='Inicio', verbose_name='Inicio'),
        ),
    ]
