# Generated by Django 5.2.3 on 2025-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_flightrequest_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En revisión'), ('approved', 'Aprobada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado de la solicitud', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('unavailable', 'No disponible')], default='available', help_text='Estado de la sesión', max_length=15, verbose_name='Estado'),
        ),
    ]
