# Generated by Django 5.2.3 on 2025-09-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_flightrequest_status_alter_flightslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightslot',
            name='block',
            field=models.CharField(choices=[('AM', 'AM'), ('M', 'M'), ('PM', 'PM')], help_text='Bloque de la sesión', max_length=2, verbose_name='Bloque'),
        ),
    ]
