# Generated by Django 5.2.3 on 2025-09-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_flightslot_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='flexible',
        ),
    ]
