# Generated by Django 5.2.3 on 2025-09-27 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_aircraft_fuel_cost'),
        ('scheduler', '0008_remove_flightrequest_flexible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightslot',
            name='training_period',
        ),
        migrations.AlterModelOptions(
            name='flightslot',
            options={'ordering': ['date', 'block', 'aircraft'], 'verbose_name': 'Slot de vuelo', 'verbose_name_plural': 'Slots de vuelo'},
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='slot',
            field=models.ForeignKey(help_text='Slot de vuelo de la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='scheduler.flightslot', verbose_name='Slot de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En revisión'), ('approved', 'Aprobada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estatus de la solicitud', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='aircraft',
            field=models.ForeignKey(blank=True, help_text='Aeronave del slot', limit_choices_to={'is_active': True, 'is_available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_slots', to='fleet.aircraft', verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='block',
            field=models.CharField(choices=[('AM', 'AM'), ('M', 'M'), ('PM', 'PM')], help_text='Bloque del slot', max_length=2, verbose_name='Bloque'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha del slot', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor del slot', limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_flight_slots', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('unavailable', 'No disponible')], default='available', help_text='Estatus del slot', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='flightslot',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Estudiante del slot', limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_flight_slots', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.CreateModel(
            name='FlightPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Inicio', verbose_name='Inicio')),
                ('end_date', models.DateField(help_text='Cierre', verbose_name='Cierre')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización', verbose_name='Fecha de actualización')),
                ('aircraft', models.ForeignKey(help_text='Aeronave', on_delete=django.db.models.deletion.CASCADE, related_name='flight_periods', to='fleet.aircraft', verbose_name='Aeronave')),
            ],
            options={
                'verbose_name': 'Periodo de vuelo',
                'verbose_name_plural': 'Periodos de vuelo',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='flightslot',
            name='flight_period',
            field=models.ForeignKey(default=None, help_text='Periodo de vuelo del slot', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.flightperiod', verbose_name='Periodo de vuelo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrainingPeriod',
        ),
    ]
