# Generated by Django 5.2.3 on 2025-09-28 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_flightslot_training_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha del slot', verbose_name='Fecha'),
        ),
    ]
