# Generated by Django 5.2.3 on 2025-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_flightslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightslot',
            name='status',
            field=models.CharField(choices=[('available', 'L'), ('pending', 'P'), ('reserved', 'R'), ('unavailable', 'NA')], default='available', help_text='Estatus del slot', max_length=15, verbose_name='Estatus'),
        ),
    ]
