# Generated by Django 5.2.3 on 2025-10-03 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_flightslot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationsFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, help_text='Monto de la multa', max_digits=4, verbose_name='Monto')),
                ('date_added', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de adición')),
                ('added_by', models.ForeignKey(blank=True, help_text='Agregado por', limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('flight_request', models.ForeignKey(blank=True, help_text='Solicitud de vuelo de la multa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_fees', to='scheduler.flightrequest', verbose_name='Solicitud de vuelo')),
            ],
            options={
                'verbose_name': 'Multa por cancelación extemporánea',
                'verbose_name_plural': 'Multas por cancelación extemporánea',
                'ordering': ['-date_added'],
            },
        ),
    ]
