# Generated by Django 5.2.3 on 2025-10-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_cancellationsfee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellationsfee',
            options={'ordering': ['-date_added'], 'verbose_name': 'Multa por cancelación', 'verbose_name_plural': 'Multas por cancelación'},
        ),
        migrations.RemoveField(
            model_name='cancellationsfee',
            name='added_by',
        ),
    ]
