# Generated by Django 5.2.3 on 2025-10-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_cancellationsfee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationsfee',
            name='flight_request',
            field=models.ForeignKey(blank=True, help_text='Solicitud de vuelo de la multa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellations_fees', to='scheduler.flightrequest', verbose_name='Solicitud de vuelo'),
        ),
    ]
