# Generated by Django 5.2.3 on 2025-10-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_alter_cancellationsfee_flight_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationsfee',
            name='flight_request',
            field=models.ForeignKey(help_text='Solicitud de vuelo de la multa', on_delete=django.db.models.deletion.CASCADE, related_name='cancellations_fees', to='scheduler.flightrequest', verbose_name='Solicitud de vuelo'),
        ),
    ]
