# Generated by Django 5.2.3 on 2025-10-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_alter_cancellationsfee_flight_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightperiod',
            name='for_navigation',
            field=models.BooleanField(default=False, help_text='Para navegación', verbose_name='Para navegación'),
        ),
        migrations.AlterField(
            model_name='flightperiod',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activo', verbose_name='Activo'),
        ),
    ]
