# Generated by Django 5.2.3 on 2025-10-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_flightperiod_for_navigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightslot',
            name='for_navigation',
            field=models.BooleanField(default=False, help_text='Slot para navegación', verbose_name='Para navegación'),
        ),
    ]
