# Generated by Django 5.2.3 on 2026-02-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_flightslot_for_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationsfee',
            name='cancelled_by_name',
            field=models.CharField(blank=True, help_text='Nombre del estudiante que canceló (conservado si se elimina la solicitud)', max_length=255, verbose_name='Cancelado por'),
        ),
    ]
