# Generated by Django 5.2.3 on 2026-07-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_student_profiles(apps, schema_editor):
    CancellationsFee = apps.get_model('scheduler', 'CancellationsFee')
    fees = CancellationsFee.objects.filter(
        student_profile__isnull=True,
        flight_request__student__student_profile__isnull=False,
    ).select_related('flight_request__student__student_profile')

    for fee in fees.iterator():
        fee.student_profile_id = fee.flight_request.student.student_profile.pk
        fee.save(update_fields=('student_profile',))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0043_studentprofile_ap_exp_date'),
        ('scheduler', '0021_add_cancelled_by_name_to_cancellationsfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationsfee',
            name='student_profile',
            field=models.ForeignKey(blank=True, help_text='Estudiante al que se aplicó la multa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_fees', to='accounts.studentprofile', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='cancellationsfee',
            name='reimbursed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reembolso'),
        ),
        migrations.AddField(
            model_name='cancellationsfee',
            name='reimbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursed_cancellation_fees', to=settings.AUTH_USER_MODEL, verbose_name='Reembolsado por'),
        ),
        migrations.RunPython(backfill_student_profiles, migrations.RunPython.noop),
    ]
