# Generated by Django 5.2.3 on 2026-03-09 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_comment_text', models.TextField()),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('ai_raw_response', models.TextField(blank=True, help_text='Optional raw response text returned by the AI model (for debugging).', null=True)),
                ('ai_result', models.JSONField(blank=True, default=dict, help_text='Structured JSON result for this individual review (tags, mini-summary, etc.).', null=True)),
                ('has_been_included_in_global_review', models.BooleanField(default=False, help_text='Indicates whether this review has ever been used to build a global review.')),
                ('first_included_in_global_review_at', models.DateTimeField(blank=True, help_text='Timestamp when this review was first included in any global review.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aura_individual_reviews_as_instructor', to=settings.AUTH_USER_MODEL)),
                ('session_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aura_individual_reviews_as_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual review',
                'verbose_name_plural': 'Individual reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('OVERALL', 'Overall training profile'), ('SIM_ONLY', 'Simulator sessions only'), ('FLIGHT_ONLY', 'Flight sessions only'), ('COURSE', 'Specific course/module'), ('CUSTOM', 'Custom scope')], default='OVERALL', help_text='Logical scope of this global review (overall, sim-only, flight-only, etc.).', max_length=20)),
                ('time_window', models.CharField(choices=[('ALL_TIME', 'All time'), ('LAST_90_DAYS', 'Last 90 days'), ('LAST_20_SESSIONS', 'Last 20 sessions'), ('CUSTOM', 'Custom window')], default='ALL_TIME', help_text='How the date/session range was selected when generating this review.', max_length=20)),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('ai_result', models.JSONField(blank=True, default=dict, help_text='Structured JSON profile (strengths, weaknesses, recommendations, summary text, etc.) produced by the AI.', null=True)),
                ('ai_raw_response', models.TextField(blank=True, help_text='Optional raw response text returned by the AI model (for debugging).', null=True)),
                ('based_on_from', models.DateTimeField(blank=True, help_text='Earliest created_at of IndividualReviews considered for this global review.', null=True)),
                ('based_on_to', models.DateTimeField(blank=True, help_text='Latest created_at of IndividualReviews considered for this global review.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aura_global_reviews', to=settings.AUTH_USER_MODEL)),
                ('individual_reviews', models.ManyToManyField(blank=True, help_text='Individual reviews that were aggregated to build this profile.', related_name='global_reviews', to='aura.individualreview')),
            ],
            options={
                'verbose_name': 'Global review',
                'verbose_name_plural': 'Global reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
