# Generated by Django 5.2.3 on 2026-03-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalreview',
            name='student',
            field=models.ForeignKey(help_text='Only users with a StudentProfile can be selected as students.', limit_choices_to=models.Q(('student_profile__isnull', False)), on_delete=django.db.models.deletion.CASCADE, related_name='aura_global_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualreview',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Only users with an InstructorProfile can be selected as instructors.', limit_choices_to=models.Q(('instructor_profile__isnull', False)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aura_individual_reviews_as_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualreview',
            name='student',
            field=models.ForeignKey(help_text='Only users with a StudentProfile can be selected as students.', limit_choices_to=models.Q(('student_profile__isnull', False)), on_delete=django.db.models.deletion.CASCADE, related_name='aura_individual_reviews_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
