# Generated by Django 5.2.3 on 2026-03-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0002_alter_globalreview_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualreview',
            name='session_content_type',
        ),
        migrations.RemoveField(
            model_name='individualreview',
            name='session_object_id',
        ),
    ]
