# Generated by Django 5.2.3 on 2026-03-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0003_remove_individualreview_session_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalreview',
            name='generation_mode',
            field=models.CharField(choices=[('FULL_REBUILD', 'Full rebuild'), ('INCREMENTAL_UPDATE', 'Incremental update')], default='FULL_REBUILD', help_text='Whether this snapshot was produced by a full rebuild or an incremental update.', max_length=30),
        ),
        migrations.AddField(
            model_name='globalreview',
            name='previous_global_review',
            field=models.ForeignKey(blank=True, help_text='Previous global review snapshot used as the baseline for an incremental update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incremental_children', to='aura.globalreview'),
        ),
        migrations.AlterField(
            model_name='globalreview',
            name='ai_result',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON profile (summary_text, up to three strengths, up to three weaknesses, domain patterns, and a short next_session_awareness note) produced by the AI.', null=True),
        ),
        migrations.AlterField(
            model_name='individualreview',
            name='ai_result',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON result for this individual review (summary, domain analysis, and recommendations).', null=True),
        ),
    ]
