# Generated by Django 5.0.6 on 2024-12-08 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.PositiveBigIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Identificación')),
                ('instructor_type', models.CharField(choices=[('ground', 'Tierra'), ('flying', 'Vuelo')], default='ground', max_length=6, verbose_name='Tipo de Instructor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'db_table': 'instructors_db',
                'ordering': ['instructor_id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.PositiveBigIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Identificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff_db',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveBigIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Identificación')),
                ('student_type', models.CharField(choices=[('ground', 'Tierra'), ('flying', 'Vuelo')], default='ground', max_length=6, verbose_name='Tipo de Estudiante')),
                ('student_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)], verbose_name='Edad')),
                ('student_course_type', models.CharField(choices=[('pp', 'PP'), ('hvi', 'HVI'), ('pc', 'PC'), ('tla', 'TLA')], default='pp', max_length=3, verbose_name='Curso')),
                ('student_course_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students_db',
                'ordering': ['student_id'],
            },
        ),
    ]
