# Generated by Django 5.0.6 on 2025-04-03 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='money_balance',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_age',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)], verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance para Línea de Vuelo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_course_edition',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edición de Curso'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='N/A', max_length=3, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='NA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_phase',
            field=models.CharField(choices=[('TIERRA', 'Escuela en tierra'), ('VUELO', 'Línea de vuelo')], default='TIERRA', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('INSTRUCTOR', 'Instructor'), ('STAFF', 'Staff')], max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='usuario'),
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='students_db',
        ),
    ]
