# Generated by Django 5.1.3 on 2024-12-10 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_flightlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_id'], 'verbose_name': 'Staff', 'verbose_name_plural': ('Staff',)},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.PositiveIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.PositiveIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Identificación'),
        ),
    ]
