# Generated by Django 5.0.6 on 2025-04-03 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('PCA', 'PCA'), ('TLA', 'TLA'), ('IVS', 'IVS'), ('OTRO', 'OTRO')], default='PCA', max_length=10, verbose_name='Tipo de licencia'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_type',
            field=models.CharField(choices=[('TIERRA', 'Escuela en tierra'), ('VUELO', 'Línea de vuelo'), ('DUAL', 'Dual')], default='TIERRA', max_length=20, verbose_name='Tipo de Instructor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(999999), django.core.validators.MaxValueValidator(100000000)], verbose_name='Cédula'),
        ),
        migrations.AlterModelTable(
            name='instructorprofile',
            table='instructors_db',
        ),
    ]
