# Generated by Django 5.0.6 on 2025-04-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instructorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Staff', 'verbose_name_plural': ('Staff',)},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterModelTable(
            name='staffprofile',
            table='staff_db',
        ),
    ]
