# Generated by Django 5.1.3 on 2024-12-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_options_alter_instructor_instructor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='balance',
            new_name='student_balance',
        ),
    ]
