# Generated by Django 5.1.3 on 2024-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_balance_student_student_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('ground', 'Tierra'), ('flying', 'Vuelo'), ('dual', 'Dual')], default='ground', max_length=6, verbose_name='Tipo de Instructor'),
        ),
    ]
