# Generated by Django 5.0.6 on 2025-04-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
