# Generated by Django 5.0.6 on 2025-04-04 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_course_edition',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Campo automático. Se actualiza según la inscripción del estudiante en un curso.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edición de Curso'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='N/A', editable=False, help_text='Campo automático. Se actualiza según la inscripción del estudiante en un curso.', max_length=3, verbose_name='Curso'),
        ),
    ]
