# Generated by Django 5.0.6 on 2025-04-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_student_course_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_course_edition',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_course_type',
        ),
    ]
