# Generated by Django 5.1.3 on 2024-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
