# Generated by Django 5.0.6 on 2025-04-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_studentprofile_student_course_edition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user__national_id'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
