# Generated by Django 5.1.3 on 2024-12-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_instructor_instructor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
    ]
