# Generated by Django 5.0.6 on 2025-04-05 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'ordering': ['-date_added', 'student_profile__user__national_id'], 'verbose_name': 'Pago de Estudiante', 'verbose_name_plural': 'Pagos de Estudiantes'},
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='studentpayment',
            table='student_payments',
        ),
    ]
