# Generated by Django 5.0.6 on 2024-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_instructor_instructor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('t', 'Tierra'), ('lv', 'Vuelo')], default='ground', max_length=6, verbose_name='Tipo de Estudiante'),
        ),
    ]
