# Generated by Django 5.0.6 on 2024-12-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('t', 'Tierra'), ('lv', 'Vuelo')], default='t', max_length=6, verbose_name='Tipo de Estudiante'),
        ),
    ]
