# Generated by Django 5.0.6 on 2025-04-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_studentpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
