# Generated by Django 5.0.6 on 2024-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
        migrations.AddField(
            model_name='student',
            name='student_phase',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Línea de vuelo', 'Línea de vuelo')], default='t', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
    ]
