# Generated by Django 5.0.6 on 2025-05-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffprofile_can_confirm_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_balance',
        ),
    ]
