# Generated by Django 5.0.6 on 2024-12-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_student_student_type_student_student_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Línea de vuelo', 'Línea de vuelo'), ('Dual', 'Dual')], default='ground', max_length=20, verbose_name='Tipo de Instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phase',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Línea de vuelo', 'Línea de vuelo')], default='Tierra', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
    ]
