# Generated by Django 5.0.6 on 2024-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_instructor_instructor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('Escuela en tierra', 'Escuela en tierra'), ('Línea de vuelo', 'Línea de vuelo'), ('Dual', 'Dual')], default='Escuela en tierra', max_length=20, verbose_name='Tipo de Instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phase',
            field=models.CharField(choices=[('Escuela en tierra', 'Escuela e tierra'), ('Línea de vuelo', 'Línea de vuelo')], default='Escuela en tierra', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
    ]
