# Generated by Django 5.0.6 on 2025-05-16 01:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_studentpayment_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_profile__can_confirm_payments': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_student_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.studentprofile', verbose_name='Estudiante'),
        ),
    ]
