# Generated by Django 5.0.6 on 2024-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_instructor_instructor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('Tierra', 'Escuela en tierra'), ('Vuelo', 'Línea de vuelo'), ('Dual', 'Dual')], default='Tierra', max_length=20, verbose_name='Tipo de Instructor'),
        ),
    ]
