# Generated by Django 5.0.6 on 2025-05-23 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentpayment_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='added_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
    ]
