# Generated by Django 5.0.6 on 2024-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_instructor_instructor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('tierra', 'Escuela en tierra'), ('vuelo', 'Línea de vuelo'), ('dual', 'Dual')], default='tierra', max_length=20, verbose_name='Tipo de Instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phase',
            field=models.CharField(choices=[('tierra', 'Escuela en tierra'), ('vuelo', 'Línea de vuelo')], default='tierra', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
    ]
