# Generated by Django 5.0.6 on 2024-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_instructor_instructor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_license_type',
            field=models.CharField(choices=[('na', 'N/A'), ('pc', 'PC'), ('tla', 'TLA')], default='pc', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F'), ('O', 'Otro')], default='m', max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_license_type',
            field=models.CharField(choices=[('na', 'N/A'), ('ap', 'AP'), ('pp', 'PP'), ('pc', 'PC'), ('tla', 'TLA')], default='ap', max_length=3, verbose_name='Tipo de licencia'),
        ),
    ]
