# Generated by Django 5.2.3 on 2025-06-27 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_studentpayment_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas de vuelo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sim_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas de simulador'),
        ),
    ]
