# Generated by Django 5.2.3 on 2025-07-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_studentprofile_flight_hours_studentprofile_sim_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='can_confirm_payments',
            field=models.BooleanField(default=False, verbose_name='Puede confirmar pagos'),
        ),
    ]
