# Generated by Django 5.0.6 on 2024-12-18 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_instructor_instructor_license_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_license_number',
            field=models.PositiveIntegerField(default='', help_text='Número de licencia sin puntos o guiones.', unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia'),
        ),
    ]
