# Generated by Django 5.0.6 on 2024-12-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_instructor_instructor_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_license_number',
        ),
    ]
