# Generated by Django 5.0.6 on 2024-12-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_instructor_instructor_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('PC', 'PC'), ('TLA', 'TLA')], default='PC', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_type',
            field=models.CharField(choices=[('TIERRA', 'Escuela en tierra'), ('VUELO', 'Línea de vuelo'), ('DUAL', 'Dual')], default='TIERRA', max_length=20, verbose_name='Tipo de Instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_course_type',
            field=models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('AP', 'AP'), ('PP', 'PP'), ('PC', 'PC'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phase',
            field=models.CharField(choices=[('TIERRA', 'Escuela en tierra'), ('VUELO', 'Línea de vuelo')], default='TIERRA', max_length=20, verbose_name='Fase de entrenamiento'),
        ),
    ]
