# Generated by Django 5.2.3 on 2025-07-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_standardize_permission_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
