# Generated by Django 5.0.6 on 2025-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_instructor_instructor_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='PCA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_course_type',
            field=models.CharField(choices=[('PP', 'PPA'), ('HVI', 'HVI'), ('PC', 'PCA')], default='PP', max_length=3, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_license_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
    ]
