# Generated by Django 5.0.6 on 2025-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_instructor_instructor_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='PPA', max_length=3, verbose_name='Curso'),
        ),
    ]
