# Generated by Django 5.2.3 on 2025-07-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='flight_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance de vuelo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sim_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance de simulador'),
        ),
    ]
