# Generated by Django 5.2.3 on 2025-08-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_studentprofile_flight_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(default='Staff', max_length=100, verbose_name='Cargo'),
        ),
    ]
