# Generated by Django 5.0.6 on 2025-04-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_student_student_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='PPA', max_length=3, verbose_name='Curso'),
        ),
    ]
