# Generated by Django 5.0.6 on 2025-04-02 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_student_student_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA'), ('IVA', 'IVA'), ('IVS', 'IVS'), ('DDV', 'DDV')], default='N/A', max_length=3, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(help_text='Número de cédula o pasaporte sin puntos o guiones.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(100000000)], verbose_name='Identificación'),
        ),
    ]
