# Generated by Django 5.2.3 on 2025-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_staffprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='flight_balance',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='sim_balance',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance'),
        ),
    ]
