# Generated by Django 5.2.3 on 2025-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_studentprofile_flight_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_confirm_payments',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_confirm_transactions',
            field=models.BooleanField(default=False, verbose_name='Puede confirmar transacciones'),
        ),
    ]
