# Generated by Django 5.2.3 on 2025-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_staffprofile_can_confirm_payments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__national_id'], 'permissions': [('can_confirm_transactions', 'Can confirm transactions'), ('can_manage_transactions', 'Can manage transactions'), ('can_manage_sms', 'Can manage SMS')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='can_confirm_transactions',
            field=models.BooleanField(default=False, help_text='Permite confirmar transacciones de estudiantes', verbose_name='Puede confirmar transacciones'),
        ),
    ]
