# Generated by Django 5.2.3 on 2025-09-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_confirm_transactions',
        ),
    ]
