# Generated by Django 5.2.3 on 2025-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_staffprofile_can_confirm_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='advanced_student',
            field=models.BooleanField(default=False, verbose_name='Estudiante avanzado'),
        ),
    ]
