# Generated by Django 5.2.3 on 2025-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_studentprofile_advanced_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='has_credit',
            field=models.BooleanField(default=False, verbose_name='Tiene crédito'),
        ),
    ]
