# Generated by Django 5.2.3 on 2025-10-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_studentprofile_has_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='has_temp_permission',
            field=models.BooleanField(default=False, help_text='Permiso temporal para solicitar vuelos sin restricciones de balance. Debe ser reactivado antes de cada vuelo.', verbose_name='Tiene permiso temporal'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='has_credit',
            field=models.BooleanField(default=False, help_text='Permiso permanente para solicitar vuelos sin restricciones de balance.', verbose_name='Tiene crédito'),
        ),
    ]
