# Generated by Django 5.2.3 on 2025-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_studentprofile_has_temp_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='flight_rate',
            field=models.DecimalField(decimal_places=1, default=130.0, max_digits=4, verbose_name='Tasa de vuelo ($/h)'),
        ),
    ]
