# Generated by Django 5.2.3 on 2025-11-04 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_studentprofile_flight_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nav_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas NAV'),
        ),
    ]
