# Generated by Django 5.2.3 on 2025-11-04 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_studentprofile_nav_flight_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='sim_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas sim'),
        ),
    ]
