# Generated by Django 5.2.3 on 2025-11-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_studentprofile_sim_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_hourly_rate',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3, verbose_name='Tasa de instrucción ($/h)'),
        ),
    ]
