# Generated by Django 5.2.3 on 2026-01-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_instructorprofile_instructor_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_license_expiration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de expiración de la licencia'),
        ),
    ]
