# Generated by Django 5.2.3 on 2026-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_studentprofile_student_license_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_license_expiration_date',
            new_name='license_exp_date',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de expiración de la licencia'),
        ),
    ]
