# Generated by Django 5.2.3 on 2026-01-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_student_license_expiration_date_studentprofile_license_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiración de la licencia'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiración de la licencia'),
        ),
    ]
