# Generated by Django 5.2.3 on 2026-02-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_instructorprofile_license_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__national_id'], 'permissions': [('can_confirm_transactions', 'Can confirm transactions'), ('can_manage_transactions', 'Can manage transactions'), ('can_manage_sms', 'Can manage SMS'), ('can_view_user_stats', 'Can view user statistics')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
