# Generated by Django 5.2.3 on 2026-03-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_staffprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__national_id'], 'permissions': [('can_confirm_transactions', 'Can confirm transactions'), ('can_manage_transactions', 'Can manage transactions'), ('can_manage_sms', 'Can manage SMS'), ('can_view_user_stats', 'Can view user statistics'), ('can_update_aura_reviews', 'Can update AURA reviews')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
