# Generated by Django 5.2.3 on 2026-03-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_staffprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_scope_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiración de la licencia de instructor'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_scope_type',
            field=models.CharField(choices=[('NA', 'N/A'), ('VUELO', 'Vuelo'), ('SIM', 'Simulador'), ('AMBOS', 'Ambos')], default='NA', max_length=10, verbose_name='Tipo de licencia de instructor'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='medical_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiración del certificado médico'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='medical_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Expiración del certificado médico'),
        ),
    ]
