# Generated by Django 5.2.3 on 2026-03-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_instructorprofile_instructor_scope_exp_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='instructor_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='instructor_scope_exp_date',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='instructor_scope_type',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='license_exp_date',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='flight_instructor_hourly_rate',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=3, verbose_name='Tasa instrucción vuelo ($/h)'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='ground_instructor_hourly_rate',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=3, verbose_name='Tasa instrucción tierra ($/h)'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='iva_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Licencia IVA'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='ivs_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Licencia IVS'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='rating_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Habilitación PA-28'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='sim_instructor_hourly_rate',
            field=models.DecimalField(decimal_places=1, default=15.0, max_digits=3, verbose_name='Tasa instrucción simulador ($/h)'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='medical_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Cert. Médico'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. de la licencia'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='medical_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Cert. Médico'),
        ),
    ]
