# Generated by Django 5.2.3 on 2026-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_instructorprofile_instructor_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='license_exp_date',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rating_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Habilitación (PA28)'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='iva_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Licencia IVA (PA28)'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='rating_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Habilitación (PA28)'),
        ),
    ]
