# Generated by Django 5.2.3 on 2026-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_studentprofile_license_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ap_exp_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Exp. Licencia AP'),
        ),
    ]
