# Generated by Django 5.2.3 on 2026-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_instructorprofile_is_chief_flight_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='is_chief_flight_instructor',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_chief_instructor',
            field=models.BooleanField(default=False, verbose_name='Jefe de instrucción'),
        ),
    ]
