# Generated by Django 5.2.3 on 2025-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_studentpayment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Monto'),
        ),
    ]
