# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_studentpayment_options_studentpayment_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentPayment',
            new_name='StudentTransaction',
        ),
    ]
