# Generated by Django 5.0.6 on 2025-04-03 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('student_first_name', models.CharField(default='', max_length=50)),
                ('student_last_name', models.CharField(default='', max_length=50)),
                ('student_license_type', models.CharField(choices=[('AP', 'AP'), ('PP', 'PP'), ('PC', 'PC'), ('TLA', 'TLA')], default='AP', max_length=3)),
                ('student_license_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('course_type', models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3)),
                ('instructor_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('instructor_first_name', models.CharField(default='', max_length=50)),
                ('instructor_last_name', models.CharField(default='', max_length=50)),
                ('instructor_license_type', models.CharField(choices=[('PC', 'PC'), ('TLA', 'TLA')], default='PC', max_length=3)),
                ('instructor_license_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('flight_date', models.DateTimeField(auto_now_add=True)),
                ('flight_rules', models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4)),
                ('solo_flight', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=3)),
                ('session_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3)),
                ('session_letter', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True)),
                ('accumulated_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('session_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aircraft_registration', models.CharField(choices=[('YV1111', 'YV1111'), ('YV2222', 'YV2222')], default='YV1111', max_length=6)),
                ('session_grade', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('pre_flight', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('checklist', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('coms', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('taxiing', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('op_safety', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('student_first_name', models.CharField(default='', max_length=50)),
                ('student_last_name', models.CharField(default='', max_length=50)),
                ('course_type', models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3)),
                ('instructor_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('instructor_first_name', models.CharField(default='', max_length=50)),
                ('instructor_last_name', models.CharField(default='', max_length=50)),
                ('flight_date', models.DateTimeField(auto_now_add=True)),
                ('flight_rules', models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4)),
                ('solo_flight', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=3)),
                ('session_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3)),
                ('session_letter', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True)),
                ('accumulated_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('session_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aircraft_registration', models.CharField(choices=[('YV1111', 'YV1111'), ('YV2222', 'YV2222')], default='YV1111', max_length=6)),
                ('session_grade', models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2)),
                ('notes', models.TextField()),
            ],
        ),
    ]
