# Generated by Django 5.0.6 on 2025-05-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightevaluation',
            old_name='checklist',
            new_name='emer_1',
        ),
        migrations.RenameField(
            model_name='flightevaluation',
            old_name='coms',
            new_name='emer_2',
        ),
        migrations.RenameField(
            model_name='flightevaluation',
            old_name='op_safety',
            new_name='emer_3',
        ),
        migrations.RenameField(
            model_name='flightevaluation',
            old_name='pre_flight',
            new_name='emer_4',
        ),
        migrations.RenameField(
            model_name='flightevaluation',
            old_name='taxiing',
            new_name='emer_5',
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='gen_7',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_10',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_11',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_12',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_7',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_8',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='inst_9',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_10',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_11',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_12',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_13',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_14',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_15',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_7',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_8',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='land_9',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_10',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_11',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_12',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_13',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_14',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_15',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_16',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_17',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_7',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_8',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='mvrs_9',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_7',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_8',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='nav_9',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_1',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_2',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_3',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_4',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_5',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='to_6',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
    ]
