# Generated by Django 5.1.3 on 2024-12-10 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateTimeField(auto_now_add=True)),
                ('instructor_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('instructor_first_name', models.CharField(default='none', max_length=50)),
                ('instructor_last_name', models.CharField(default='none', max_length=50)),
                ('instructor_license_type', models.CharField(choices=[('type1', 'Tipo 1'), ('type2', 'Tipo 2'), ('type3', 'Tipo 3')], max_length=10)),
                ('instructor_license_number', models.PositiveIntegerField()),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('student_first_name', models.CharField(default='none', max_length=50)),
                ('student_last_name', models.CharField(default='none', max_length=50)),
                ('student_license_number', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('pp', 'PP'), ('hvi', 'HVI'), ('pc', 'PC'), ('tla', 'TLA')], default='none', max_length=10)),
                ('flight_rules', models.CharField(choices=[('vfr', 'VFR'), ('ifr', 'IFR'), ('dual', 'Dual')], default='none', max_length=10)),
                ('solo_flight', models.BooleanField()),
                ('session_number', models.CharField(default='none', max_length=5)),
                ('accumulated_flight_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session_flight_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aircraft_registration', models.CharField(default='none', max_length=6)),
                ('session_grade', models.CharField(choices=[('s', 'S'), ('ns', 'NS'), ('ne', 'NE')], default='none', max_length=2)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='flightlog',
            old_name='flight_hours',
            new_name='session_flight_hours',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='student',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='aircraft_registration',
            field=models.CharField(default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='course_type',
            field=models.CharField(choices=[('pp', 'PP'), ('hvi', 'HVI'), ('pc', 'PC'), ('tla', 'TLA')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='flight_rules',
            field=models.CharField(choices=[('vfr', 'VFR'), ('ifr', 'IFR'), ('dual', 'Dual')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='instructor_first_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='instructor_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightlog',
            name='instructor_last_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='session_grade',
            field=models.CharField(choices=[('s', 'Standard'), ('ns', 'Non-standard')], default='none', max_length=2),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='session_number',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='solo_flight',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightlog',
            name='student_first_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='student_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightlog',
            name='student_last_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='total_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
