# Generated by Django 5.0.6 on 2024-12-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_flightevaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation',
            name='student_license_type',
            field=models.CharField(choices=[('type1', 'Tipo 1'), ('type2', 'Tipo 2'), ('type3', 'Tipo 3')], default='none', max_length=10),
        ),
    ]
