# Generated by Django 5.0.6 on 2024-12-17 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_flightevaluation_student_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='course_type',
            field=models.CharField(choices=[('pp', 'PP'), ('hvi', 'HVI'), ('pc', 'PC'), ('tla', 'TLA')], default='pp', max_length=10),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='instructor_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='instructor_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='instructor_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='instructor_license_type',
            field=models.CharField(choices=[('pc', 'PC'), ('tla', 'TLA')], default='pc', max_length=3),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='student_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='student_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='student_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='student_license_type',
            field=models.CharField(choices=[('ap', 'AP'), ('pp', 'PP'), ('pc', 'PC')], default='ap', max_length=3),
        ),
    ]
