# Generated by Django 5.0.6 on 2024-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_alter_flightevaluation_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='aircraft_registration',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='flight_rules',
            field=models.CharField(choices=[('vfr', 'VFR'), ('ifr', 'IFR'), ('dual', 'Dual')], default='vfr', max_length=4),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_grade',
            field=models.CharField(choices=[('s', 'S'), ('ns', 'NS'), ('ne', 'NE')], default='ne', max_length=2),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_number',
            field=models.CharField(default='', max_length=5),
        ),
    ]
