# Generated by Django 5.2.3 on 2025-06-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_flightevaluation100_120'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightEvaluation120_170',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID alumno')),
                ('student_first_name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('student_last_name', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('student_license_type', models.CharField(choices=[('AP', 'AP'), ('PP', 'PP'), ('PC', 'PC'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia')),
                ('student_license_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia')),
                ('course_type', models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3, verbose_name='Tipo de curso')),
                ('instructor_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID instructor')),
                ('instructor_first_name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('instructor_last_name', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('instructor_license_type', models.CharField(choices=[('PC', 'PC'), ('TLA', 'TLA')], default='PC', max_length=3, verbose_name='Tipo de licencia')),
                ('instructor_license_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia')),
                ('flight_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de vuelo')),
                ('flight_rules', models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4, verbose_name='Reglas de vuelo')),
                ('solo_flight', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=3, verbose_name='Vuelo solo')),
                ('session_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3, verbose_name='Número')),
                ('session_letter', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True, verbose_name='Repetición de sesión')),
                ('accumulated_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas')),
                ('session_flight_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo')),
                ('aircraft_registration', models.CharField(choices=[('YV204E', 'YV204E'), ('YV206E', 'YV206E')], default='YV204E', max_length=6, verbose_name='Aeronave')),
                ('session_grade', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión')),
                ('pre_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo VFR/IFR')),
                ('pre_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Insp. pre-vuelo / briefing (Serv/WX/NOTAMs)')),
                ('pre_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist')),
                ('pre_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4) (ATIS/Clearance)')),
                ('pre_5', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje/hotspot/lectura taxi-route')),
                ('pre_6', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo')),
                ('to_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal')),
                ('to_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado')),
                ('to_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta y/o suave')),
                ('to_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)')),
                ('to_5', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4)')),
                ('to_6', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID (salidas vectorizadas)')),
                ('inst_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo/operacional (IFR)')),
                ('inst_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación IFR')),
                ('inst_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4) (ATIS/Clearance)')),
                ('inst_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radionavegación convencional/RNAV')),
                ('inst_5', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viraje de procedimiento (45x180) (base)')),
                ('inst_6', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arcos/DME')),
                ('inst_7', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de no-precisión')),
                ('inst_8', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos APV (demo)')),
                ('inst_9', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de precisión')),
                ('inst_10', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de aprox. frustrada')),
                ('inst_11', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Circuitos de espera')),
                ('land_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal')),
                ('land_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada')),
                ('land_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada')),
                ('land_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución de procedimiento IFR')),
                ('land_5', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Transición IFR a referencias visuales')),
                ('land_6', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento taxi out')),
                ('land_7', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo')),
                ('emer_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Windshear')),
                ('emer_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Evento TCAS')),
                ('emer_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Incapacitación del piloto')),
                ('emer_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Sin radiocomunicaciones abordo (NORDO)')),
                ('gen_1', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio')),
                ('gen_2', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo')),
                ('gen_3', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo')),
                ('gen_4', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo')),
                ('gen_5', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones')),
                ('gen_6', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV')),
                ('gen_7', models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general')),
                ('notes', models.TextField(verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Flight Evaluation 120-170',
                'verbose_name_plural': 'Flight Evaluations 120-170',
            },
        ),
        migrations.AlterModelOptions(
            name='flightevaluation0_100',
            options={'verbose_name': 'Flight Evaluation 0-100', 'verbose_name_plural': 'Flight Evaluations 0-100'},
        ),
        migrations.AlterModelOptions(
            name='flightevaluation100_120',
            options={'verbose_name': 'Flight Evaluation 100-120', 'verbose_name_plural': 'Flight Evaluations 100-120'},
        ),
        migrations.AlterModelOptions(
            name='flightlog',
            options={'verbose_name': 'Flight Log', 'verbose_name_plural': 'Flight Logs'},
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='aircraft_registration',
            field=models.CharField(choices=[('YV204E', 'YV204E'), ('YV206E', 'YV206E')], default='YV204E', max_length=6, verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='course_type',
            field=models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y juicio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Identificación de la anormalidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos memory-items y anormales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Control de la aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Navegación (plan alterno en ruta)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='flight_rules',
            field=models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4, verbose_name='Reglas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID instructor'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_license_type',
            field=models.CharField(choices=[('PC', 'PC'), ('TLA', 'TLA')], default='PC', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_10',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Situaciones anormales en el circuito'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de circuito'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Maniobra de derrape (demo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Configuración de aterrizaje (limpio/full flaps)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje corto/campo suave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_8',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Toque y despegue'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_9',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Go-around'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de compensadores'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_10',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Efecto del P-factor'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_11',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Chandelles'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_12',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='8 perezosos'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_13',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre pilones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_14',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre carreteras'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_15',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Descenso c/s potencia (glide speed)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_16',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ubicación espacial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_17',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual (UPSET)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_18',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Precisión de 090, 180, 360 y 720'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de nivelado (control y comportamiento)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelto recto nivelado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes de 10, 20, 30 y 45'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes ascenso/descenso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelo lento'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida limpia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_8',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida config. despegue y aterrizaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_9',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida secundaria'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Briefing de pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación/Tablas de performance'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo operacional (TOC-TOD)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones en ruta (reportes)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Orientación espacial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de radioayudas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='notes',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo VFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Inspección pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_grade',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='solo_flight',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID alumno'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PP', 'PP'), ('PC', 'PC'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal/Estático/Rolling'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta y/o campo blando'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución salida visual'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo/operacional (IFR)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_10',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de aprox. frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_11',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Circuitos de espera'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones IFR (reportes)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viraje de procedimiento (45x180) (base)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arcos/DME'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de no-precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_8',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos APV (demo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_9',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='aircraft_registration',
            field=models.CharField(choices=[('YV204E', 'YV204E'), ('YV206E', 'YV206E')], default='YV204E', max_length=6, verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Maniobra tipo S (SA, SB, SC, SD)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_10',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes inversión curso (45x180) (80x260) (base)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_11',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Patrón de juego'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes cronometrados (1 RST / 1/2 RST)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual (UPSET)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Serie de virajes'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Cambios de velocidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción de radiales (IB/OB)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Interceptación de marcaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_8',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de instrumentos de navegación (chequeos)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_9',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Chequeo cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='course_type',
            field=models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y juicio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Identificación de la anormalidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos memory-items y anormales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Recuperación de pérdida por instrumentos'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Panel parcial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='flight_rules',
            field=models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4, verbose_name='Reglas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID instructor'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_license_type',
            field=models.CharField(choices=[('PC', 'PC'), ('TLA', 'TLA')], default='PC', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución de procedimiento IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Transición IFR a referencias visuales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_7',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='notes',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Inspección pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_grade',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='solo_flight',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID alumno'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_license_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PP', 'PP'), ('PC', 'PC'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_1',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_2',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_3',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_4',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_5',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_6',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='aircraft_registration',
            field=models.CharField(choices=[('YV204E', 'YV204E'), ('YV206E', 'YV206E')], default='YV204E', max_length=6, verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='course_type',
            field=models.CharField(choices=[('PP', 'PP'), ('HVI', 'HVI'), ('PC', 'PC'), ('TLA', 'TLA')], default='PP', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_rules',
            field=models.CharField(choices=[('VFR', 'VFR'), ('IFR', 'IFR'), ('DUAL', 'Dual')], default='VFR', max_length=4, verbose_name='Reglas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='instructor_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='instructor_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID instructor'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='instructor_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='notes',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_grade',
            field=models.CharField(choices=[('NS', 'NS'), ('S', 'S'), ('SS', 'SS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('E', 'E')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=3, verbose_name='Sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='solo_flight',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='student_first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='student_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID alumno'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='student_last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
    ]
