# Generated by Django 5.0.6 on 2024-12-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_alter_flightevaluation_aircraft_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='student_license_type',
            field=models.CharField(choices=[('ap', 'AP'), ('pp', 'PP'), ('pc', 'PC'), ('tla', 'TLA')], default='ap', max_length=3),
        ),
    ]
