# Generated by Django 5.0.6 on 2024-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0006_alter_flightevaluation_student_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='aircraft_registration',
            field=models.CharField(choices=[('yv1111', 'YV1111'), ('yv2222', 'YV2222')], default='yv1111', max_length=6),
        ),
    ]
