# Generated by Django 5.0.6 on 2024-12-17 18:29

import fms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_alter_flightevaluation_aircraft_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_number',
            field=models.CharField(choices=fms.models.FlightEvaluation.generate_choices, default='1', max_length=3),
        ),
    ]
