# Generated by Django 5.2.3 on 2025-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_simevaluation_simulatorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightevaluation0_100',
            options={'verbose_name': 'Evaluación de vuelo 0-100', 'verbose_name_plural': 'Evaluaciones de vuelo 0-100'},
        ),
        migrations.AlterModelOptions(
            name='flightevaluation100_120',
            options={'verbose_name': 'Evaluación de vuelo 100-120', 'verbose_name_plural': 'Evaluaciones de vuelo 100-120'},
        ),
        migrations.AlterModelOptions(
            name='flightevaluation120_170',
            options={'verbose_name': 'Evaluación de vuelo 120-170', 'verbose_name_plural': 'Evaluaciones de vuelo 120-170'},
        ),
        migrations.AlterModelOptions(
            name='flightlog',
            options={'verbose_name': 'Bitácora de vuelo', 'verbose_name_plural': 'Bitácoras de vuelo'},
        ),
        migrations.AlterModelOptions(
            name='simevaluation',
            options={'verbose_name': 'Evaluación de simulador', 'verbose_name_plural': 'Evaluaciones de simulador'},
        ),
        migrations.AlterModelOptions(
            name='simulatorlog',
            options={'verbose_name': 'Bitácora de simulador', 'verbose_name_plural': 'Bitácoras de simulador'},
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y juicio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Identificación de la anormalidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos memory-items y anormales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Control de la aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Navegación (plan alterno en ruta)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='emer_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='gen_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='instructor_license_type',
            field=models.CharField(choices=[('PCA', 'PCA'), ('TLA', 'TLA')], default='PCA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Situaciones anormales en el circuito'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de circuito'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Maniobra de derrape (demo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Configuración de aterrizaje (limpio/full flaps)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje corto/campo suave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Toque y despegue'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='land_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Go-around'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de compensadores'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Efecto del P-factor'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Chandelles'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_12',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='8 perezosos'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_13',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre pilones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_14',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre carreteras'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_15',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Descenso c/s potencia (glide speed)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_16',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ubicación espacial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_17',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual (UPSET)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_18',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Precisión de 090, 180, 360 y 720'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de nivelado (control y comportamiento)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelto recto nivelado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes de 10, 20, 30 y 45'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes ascenso/descenso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelo lento'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida limpia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida config. despegue y aterrizaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='mvrs_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida secundaria'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Briefing de pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación/Tablas de performance'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo operacional (TOC-TOD)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones en ruta (reportes)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Orientación espacial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='nav_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de radioayudas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo VFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Inspección pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='pre_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal/Estático/Rolling'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta y/o campo blando'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='to_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución salida visual'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo/operacional (IFR)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de aprox. frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Circuitos de espera'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones IFR (reportes)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viraje de procedimiento (45x180) (base)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arcos/DME'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de no-precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos APV (demo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='a_ifr_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Maniobra tipo S (SA, SB, SC, SD)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes inversión curso (45x180) (80x260) (base)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Patrón de juego'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes cronometrados (1 RST / 1/2 RST)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual (UPSET)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Serie de virajes'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Cambios de velocidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción de radiales (IB/OB)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Interceptación de marcaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de instrumentos de navegación (chequeos)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='b_ifr_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Chequeo cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y juicio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Identificación de la anormalidad'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos memory-items y anormales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Recuperación de pérdida por instrumentos'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='emer_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Panel parcial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='gen_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='instructor_license_type',
            field=models.CharField(choices=[('PCA', 'PCA'), ('TLA', 'TLA')], default='PCA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución de procedimiento IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Transición IFR a referencias visuales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='land_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Inspección pre-vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='pre_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones aeronáuticas IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='to_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='emer_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Windshear'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='emer_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Evento TCAS'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='emer_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Incapacitación del piloto'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='emer_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Sin radiocomunicaciones abordo (NORDO)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud y criterio'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Seguridad de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Disciplina de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento de la aeronave y limitaciones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='gen_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Juicio general'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo/operacional (IFR)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de aprox. frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Circuitos de espera'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4) (ATIS/Clearance)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radionavegación convencional/RNAV'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viraje de procedimiento (45x180) (base)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arcos/DME'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de no-precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos APV (demo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='inst_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimientos de precisión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='instructor_license_type',
            field=models.CharField(choices=[('PCA', 'PCA'), ('TLA', 'TLA')], default='PCA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aterrizaje normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación estabilizada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución de procedimiento IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Transición IFR a referencias visuales'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento taxi out'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='land_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de vuelo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo VFR/IFR'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Insp. pre-vuelo / briefing (Serv/WX/NOTAMs)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso correcto de checklist'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4) (ATIS/Clearance)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de rodaje/hotspot/lectura taxi-route'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='pre_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Anormalidades en el encendido y taxeo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Normal'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Viento cruzado'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pista corta y/o suave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso (potencia/velocidad/rumbo)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comns. IFR (ICAO 4)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='to_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución SID (salidas vectorizadas)'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Instrucciones del ATC'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de frecuencias apropiadas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_12',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Interpretación de cartas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_13',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución del procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_14',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_15',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_17',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Instrucciones del ATC'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_18',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de frecuencias apropiadas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_19',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de frecuencias apropiadas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_20',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Interpretación de cartas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_21',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución del procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_22',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_23',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Interpretación de cartas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución del procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Aproximación frustrada'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='app_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Instrucciones del ATC'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='dep_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de radioayudas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='dep_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='dep_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Instrucciones del ATC'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='dep_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento del SID'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='dep_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución del SID'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='go_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ejecución del procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='go_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicación'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ascenso'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Panel parcial'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida (conf. limpia)'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_12',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida (conf. despegue)'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_13',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida (conf. aterrizaje)'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica de nivelado'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelo recto y nivelado'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes estándar'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes 30° de banqueo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes 45° de banqueo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S vertical'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Cambios de velocidad'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='inst_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Cambios de configuración'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='instructor_license_type',
            field=models.CharField(choices=[('PCA', 'PCA'), ('TLA', 'TLA')], default='PCA', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso del transponder'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Teoría de vuelo instrumental'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Lectura e interpretación de cartas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso del computador'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento RAV'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Conocimiento general'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='misc_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de los compensadores'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='pre_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Preparación del vuelo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='pre_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Lista de chequeo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='pre_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Instrucciones del ATC'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Sintonía para la identificación'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arco DME'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica general'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_12',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Sintonía para la identificación'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_13',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción IB'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_14',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción OB'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_15',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_16',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Entrada correcta'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_17',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Patrón de espera'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_18',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes de procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_19',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Estimación y corrección de tiempo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción IB'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_20',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_21',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Arco DME'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_22',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Técnica general'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Intercepción OB'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Entrada correcta'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Patrón de espera'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes de procedimiento'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Estimación y corrección de tiempo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='radio_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Radiocomunicaciones'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default='AP', max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='to_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de potencia'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='to_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Rumbo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='to_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Actitud'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='to_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='to_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Proc. de despegue'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='upset_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='upset_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Procedimiento de recuperación'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='upset_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de instrumentos'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default='PPA', max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Calificación de la sesión'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, null=True, verbose_name='Repetición de sesión'),
        ),
    ]
