# Generated by Django 5.2.3 on 2025-06-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_alter_flightevaluation0_100_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default=None, max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default=None, max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default=None, max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default=None, max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default=None, max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default=None, max_length=3, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='course_type',
            field=models.CharField(choices=[('PPA', 'PPA'), ('HVI', 'HVI'), ('PCA', 'PCA')], default=None, max_length=3, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='student_license_type',
            field=models.CharField(choices=[('AP', 'AP'), ('PPA', 'PPA'), ('PCA', 'PCA'), ('TLA', 'TLA')], default=None, max_length=3, verbose_name='Tipo de licencia'),
        ),
    ]
