# Generated by Django 5.0.6 on 2024-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_alter_flightevaluation_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation',
            name='session_letter',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('e', 'E')], default='', max_length=1),
        ),
    ]
