# Generated by Django 5.0.6 on 2024-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0009_flightevaluation_session_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_letter',
            field=models.CharField(choices=[('', ''), ('a', 'A'), ('b', 'B'), ('e', 'E')], default='', max_length=1),
        ),
    ]
