# Generated by Django 5.0.6 on 2024-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0010_alter_flightevaluation_session_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='solo_flight',
            field=models.CharField(choices=[('y', 'Y'), ('n', 'N')], default='y', max_length=3),
        ),
    ]
