# Generated by Django 5.1.3 on 2024-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0011_alter_flightevaluation_solo_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_letter',
            field=models.CharField(choices=[('', ''), ('a', 'A'), ('b', 'B'), ('e', 'E')], default='', max_length=1, null=True),
        ),
    ]
