# Generated by Django 5.1.3 on 2024-12-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0012_alter_flightevaluation_session_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('a', 'A'), ('b', 'B'), ('e', 'E')], default='', max_length=1, null=True),
        ),
    ]
