# Generated by Django 5.0.6 on 2024-12-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0014_remove_flightlog_total_flight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
