# Generated by Django 5.2.3 on 2025-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0014_alter_flightlog_evaluation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='accumulated_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de vuelo acumuladas'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='accumulated_sim_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de simulador acumuladas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_sim_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='accumulated_sim_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de simulador acumuladas'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_sim_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas sesión'),
        ),
    ]
