# Generated by Django 5.2.3 on 2025-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0015_alter_flightevaluation0_100_accumulated_flight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='SI', max_length=3, verbose_name='Vuelo solo'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='pre_solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=3, verbose_name='Sesión pre-solo'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='pre_solo_flight',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=3, verbose_name='Sesión pre-solo'),
        ),
    ]
