# Generated by Django 5.0.6 on 2024-12-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0015_alter_flightlog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
