# Generated by Django 5.0.6 on 2024-12-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0016_alter_flightevaluation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='notes',
            field=models.TextField(),
        ),
    ]
