# Generated by Django 5.2.3 on 2025-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0016_alter_flightevaluation0_100_solo_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Repetición de la sesión'),
        ),
    ]
