# Generated by Django 5.2.3 on 2025-07-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0017_alter_flightevaluation0_100_session_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='simevaluation',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='simulatorlog',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
    ]
