# Generated by Django 5.0.6 on 2025-01-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0017_alter_flightevaluation_notes_alter_flightlog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation',
            name='session_grade',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='flightevaluation',
            name='solo_flight',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='session_grade',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='solo_flight',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=3),
        ),
    ]
