# Generated by Django 5.2.3 on 2025-07-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0018_flightevaluation0_100_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='notes',
            field=models.CharField(max_length=250, verbose_name='Notas'),
        ),
    ]
