# Generated by Django 5.0.6 on 2025-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0019_alter_flightevaluation_session_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation',
            name='checklist',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='coms',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='op_safety',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='pre_flight',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='flightevaluation',
            name='taxiing',
            field=models.CharField(choices=[('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2),
        ),
    ]
