# Generated by Django 5.2.3 on 2025-07-11 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0020_remove_flightevaluation0_100_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
    ]
