# Generated by Django 5.2.3 on 2025-07-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0021_alter_flightevaluation0_100_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='HVI-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PCA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='course_type',
            field=models.CharField(choices=[('N/A', 'No inscrito'), ('PPA-T', 'PPA-T'), ('PPA-P', 'PPA-P'), ('HVI-T', 'HVI-T'), ('HVI-P', 'HVI-P'), ('PCA-T', 'PCA-T'), ('PCA-P', 'PCA-P'), ('IVA-T', 'IVA-T'), ('IVA-P', 'IVA-P'), ('IVS-T', 'IVS-T'), ('IVS-P', 'IVS-P'), ('RCL', 'RCL')], default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
    ]
