# Generated by Django 5.2.3 on 2025-07-25 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0022_alter_flightevaluation0_100_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='flight_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
