# Generated by Django 5.2.3 on 2025-07-25 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0023_alter_flightlog_flight_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightevaluation0_100',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='flightevaluation100_120',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='flightevaluation120_170',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='flight_date',
        ),
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
