# Generated by Django 5.2.3 on 2025-07-28 19:00

from django.db import migrations


def cleanup_orphaned_permissions(apps, schema_editor):
    """
    Clean up orphaned permissions from the old deleted FlightEvaluation model.
    """
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Try to get the content type for the old FlightEvaluation model
    try:
        old_flightevaluation_ct = ContentType.objects.get(
            app_label='fms',
            model='flightevaluation'
        )
        
        # Delete all permissions associated with the old model
        Permission.objects.filter(content_type=old_flightevaluation_ct).delete()
        
        # Also delete the content type itself
        old_flightevaluation_ct.delete()
        
    except ContentType.DoesNotExist:
        # Content type doesn't exist, which means it was already cleaned up
        pass


def reverse_cleanup_orphaned_permissions(apps, schema_editor):
    """
    Reverse the cleanup (not really needed but good practice).
    Note: We can't really recreate the old model, so this is mostly for completeness.
    """
    # This would require recreating the old FlightEvaluation model
    # which we don't want to do, so we'll leave this empty
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0026_fix_permission_names'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_permissions,
            reverse_cleanup_orphaned_permissions
        ),
    ]
