# Generated by Django 5.2.3 on 2025-07-31 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_aircraft_total_cycles'),
        ('fms', '0027_cleanup_orphaned_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='simevaluation',
            name='simulator_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.simulator', verbose_name='Simulador (New)'),
        ),
        migrations.AddField(
            model_name='simulatorlog',
            name='simulator_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.simulator', verbose_name='Simulador (New)'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=3, verbose_name='Número'),
        ),
    ]
