# Generated by Django 5.2.3 on 2025-07-31 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_aircraft_total_cycles'),
        ('fms', '0029_migrate_simulator_data'),
    ]

    operations = [
        # Remove old simulator CharField from SimEvaluation
        migrations.RemoveField(
            model_name='simevaluation',
            name='simulator',
        ),
        # Remove old simulator CharField from SimulatorLog
        migrations.RemoveField(
            model_name='simulatorlog',
            name='simulator',
        ),
        # Rename simulator_new to simulator in SimEvaluation
        migrations.RenameField(
            model_name='simevaluation',
            old_name='simulator_new',
            new_name='simulator',
        ),
        # Rename simulator_new to simulator in SimulatorLog
        migrations.RenameField(
            model_name='simulatorlog',
            old_name='simulator_new',
            new_name='simulator',
        ),
        # Make simulator field required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='simevaluation',
            name='simulator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='fleet.simulator',
                verbose_name='Simulador'
            ),
        ),
        migrations.AlterField(
            model_name='simulatorlog',
            name='simulator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='fleet.simulator',
                verbose_name='Simulador'
            ),
        ),
    ] 