# Generated by Django 5.2.3 on 2025-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0030_remove_old_simulator_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='simevaluation',
            name='session_type',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DUAL', 'DUAL')], default='SIMPLE', max_length=6, verbose_name='Tipo de sesión'),
        ),
    ]
