# Generated by Django 5.2.3 on 2025-08-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0031_simevaluation_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simevaluation',
            name='session_type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Dual', 'Dual')], default='Simple', max_length=6, verbose_name='Tipo de sesión'),
        ),
    ]
