# Generated by Django 5.2.3 on 2025-08-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_simulator_hourly_rate_and_more'),
        ('fms', '0032_alter_simevaluation_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aircraft (New)'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aircraft (New)'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aircraft (New)'),
        ),
    ]
