# Generated by Django 5.2.3 on 2025-08-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_simulator_hourly_rate_and_more'),
        ('fms', '0034_migrate_aircraft_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave nueva'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave nueva'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='aircraft_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave nueva'),
        ),
    ]
