# Generated by Django 5.2.3 on 2025-08-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_simulator_hourly_rate_and_more'),
        ('fms', '0035_alter_flightevaluation0_100_aircraft_new_and_more'),
    ]

    operations = [
        # Remove the old aircraft_registration CharField
        migrations.RemoveField(
            model_name='flightevaluation0_100',
            name='aircraft_registration',
        ),
        migrations.RemoveField(
            model_name='flightevaluation100_120',
            name='aircraft_registration',
        ),
        migrations.RemoveField(
            model_name='flightevaluation120_170',
            name='aircraft_registration',
        ),
        # Rename aircraft_new to aircraft (preserves data)
        migrations.RenameField(
            model_name='flightevaluation0_100',
            old_name='aircraft_new',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='flightevaluation100_120',
            old_name='aircraft_new',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='flightevaluation120_170',
            old_name='aircraft_new',
            new_name='aircraft',
        ),
    ]
