# Generated by Django 5.2.3 on 2025-08-11 00:30
# Renumbered from 0038 to 0037 for sequential migration numbering

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0036_remove_flightevaluation0_100_aircraft_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='aircraft_registration',
            field=models.CharField(blank=True, choices=[('YV204E', 'YV204E'), ('YV206E', 'YV206E')], default='YV204E', max_length=6, null=True, verbose_name='Aeronave'),
        ),
    ]
