# Generated by Django 5.2.3 on 2025-08-11 01:18
# Renumbered from 0039 to 0038 for sequential migration numbering

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0037_alter_flightlog_aircraft_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
    ]
