# Generated by Django 5.2.3 on 2025-08-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_simulator_hourly_rate_and_more'),
        ('fms', '0038_make_aircraft_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
    ]
