# Generated by Django 5.2.3 on 2025-08-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0039_flightlog_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='aircraft_registration',
        ),
    ]
