# Generated by Django 5.2.3 on 2025-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0040_remove_flightlog_aircraft_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='final_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro final'),
        ),
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='fuel_consumed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Combustible consumido (litros)'),
        ),
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='initial_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro inicial'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Horas sesión'),
        ),
    ]
