# Generated by Django 5.2.3 on 2025-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0041_flightevaluation0_100_final_hourmeter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='final_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro final'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='fuel_consumed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Combustible consumido (litros)'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='initial_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro inicial'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='final_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro final'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='fuel_consumed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Combustible consumido (litros)'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='initial_hourmeter',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro inicial'),
        ),
    ]
