# Generated by Django 5.2.3 on 2025-08-27 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_aircraft_fuel_cost'),
        ('fms', '0043_remove_log_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='ID piloto')),
                ('pilot_first_name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('pilot_last_name', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('pilot_license_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Número de licencia')),
                ('flight_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('flight_reason', models.CharField(choices=[('TRF', 'Traslado'), ('FLT', 'Chequeo'), ('OTH', 'Otro')], default='TRF', max_length=3, verbose_name='Motivo')),
                ('initial_hourmeter', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro inicial')),
                ('final_hourmeter', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horómetro final')),
                ('fuel_consumed', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Combustible consumido (litros)')),
                ('flight_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Horas sesión')),
                ('comments', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave')),
            ],
            options={
                'verbose_name': 'Reporte de vuelo',
                'verbose_name_plural': 'Reportes de vuelo',
            },
        ),
    ]
