# Generated by Django 5.2.3 on 2025-08-27 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0044_flightreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreport',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
    ]
