# Generated by Django 5.2.3 on 2025-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0045_alter_flightreport_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='S', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='S', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='S', max_length=2, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_grade',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='S', max_length=2, verbose_name='Nota'),
        ),
    ]
