# Generated by Django 5.2.3 on 2025-09-29 19:48

import django.core.validators
import fms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0047_alter_flightevaluation0_100_session_flight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), fms.models.SpanishMaxValueValidator(10.0, 'Las horas de la sesión no pueden exceder 10 horas.')], verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), fms.models.SpanishMaxValueValidator(10.0, 'Las horas de la sesión no pueden exceder 10 horas.')], verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), fms.models.SpanishMaxValueValidator(10.0, 'Las horas de la sesión no pueden exceder 10 horas.')], verbose_name='Horas sesión'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='session_sim_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), fms.models.SpanishMaxValueValidator(4.0, 'Las horas de la sesión no pueden exceder 4 horas.')], verbose_name='Horas sesión'),
        ),
    ]
