# Generated by Django 5.2.3 on 2025-09-29 20:31

import django.core.validators
import fms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0049_alter_simevaluation_session_sim_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreport',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), fms.models.SpanishMaxValueValidator(10.0, 'Las horas de la sesión no pueden exceder 10 horas.')], verbose_name='Horas sesión'),
        ),
    ]
