# Generated by Django 5.2.3 on 2025-11-20 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_aircraft_hour_correction_factor'),
        ('fms', '0050_alter_flightreport_flight_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportee_first_name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('reportee_last_name', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('discrepancy_type', models.CharField(choices=[('ENGINE', 'Motor'), ('COMNS', 'Comunicaciones'), ('AVIONICS', 'Aviónica'), ('ELECTRICAL', 'Eléctrico'), ('STRUCTURAL', 'Estructural'), ('OTHER', 'Otro')], default='ENGINE', max_length=20, verbose_name='Tipo de discrepancia')),
                ('discrepancy_description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción de la discrepancia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completado'), ('INVALID', 'Anulado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave')),
            ],
            options={
                'verbose_name': 'Reporte de discrepancia',
                'verbose_name_plural': 'Reportes de discrepancia',
            },
        ),
    ]
