# Generated by Django 5.2.3 on 2025-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0051_discrepancyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancyreport',
            name='discrepancy_type',
            field=models.CharField(blank=True, choices=[('ENGINE', 'Motor'), ('COMNS', 'Comunicaciones'), ('AVIONICS', 'Aviónica'), ('ELECTRICAL', 'Eléctrico'), ('STRUCTURAL', 'Estructural'), ('OTHER', 'Otro')], default=None, max_length=20, null=True, verbose_name='Tipo de discrepancia'),
        ),
    ]
