# Generated by Django 5.2.3 on 2026-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0052_alter_discrepancyreport_discrepancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='aura_processed',
            field=models.BooleanField(default=False, help_text='Indica si esta sesión de vuelo ya fue procesada por AURA.', verbose_name='Procesado por AURA'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='aura_processed',
            field=models.BooleanField(default=False, help_text='Indica si esta sesión de vuelo ya fue procesada por AURA.', verbose_name='Procesado por AURA'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='aura_processed',
            field=models.BooleanField(default=False, help_text='Indica si esta sesión de vuelo ya fue procesada por AURA.', verbose_name='Procesado por AURA'),
        ),
        migrations.AddField(
            model_name='simevaluation',
            name='aura_processed',
            field=models.BooleanField(default=False, help_text='Indica si esta sesión de simulador ya fue procesada por AURA.', verbose_name='Procesado por AURA'),
        ),
    ]
