# Generated by Django 5.2.3 on 2026-03-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0003_remove_individualreview_session_content_type_and_more'),
        ('fms', '0053_flightevaluation0_100_aura_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation0_100',
            name='aura_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_eval_0_100', to='aura.individualreview', verbose_name='Revisión AURA'),
        ),
        migrations.AddField(
            model_name='flightevaluation100_120',
            name='aura_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_eval_100_120', to='aura.individualreview', verbose_name='Revisión AURA'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='aura_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_eval_120_170', to='aura.individualreview', verbose_name='Revisión AURA'),
        ),
        migrations.AddField(
            model_name='simevaluation',
            name='aura_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_evaluation', to='aura.individualreview', verbose_name='Revisión AURA'),
        ),
    ]
