# Generated by Django 5.2.3 on 2026-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0054_flightevaluation0_100_aura_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Briefing de pre-vuelo'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Planificación/Tablas de performance'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Plan de vuelo operacional (TOC-TOD)'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Comunicaciones en ruta (reportes)'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Orientación espacial'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='nav_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Uso de radioayudas'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32')], default='1', max_length=3, verbose_name='Número'),
        ),
    ]
