# Generated by Django 5.2.3 on 2026-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0055_flightevaluation120_170_nav_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_1',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Virajes ascenso/descenso'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_10',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre carreteras'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_11',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Ubicación espacial'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_12',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Reconocimiento de actitud inusual (UPSET)'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_13',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Precisión de 090, 180, 360 y 720'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_2',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Vuelo lento'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_3',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida limpia'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_4',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida config. despegue y aterrizaje'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_5',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Pérdida secundaria'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_6',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Efecto del P-factor'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_7',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='Chandelles'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_8',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='8 perezosos'),
        ),
        migrations.AddField(
            model_name='flightevaluation120_170',
            name='mvrs_9',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('NS', 'NS'), ('NE', 'NE')], default='NE', max_length=2, verbose_name='S sobre pilones'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='session_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33')], default='1', max_length=3, verbose_name='Número'),
        ),
    ]
