# Generated by Django 5.2.3 on 2026-05-29 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0056_flightevaluation120_170_mvrs_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios'),
        ),
    ]
