# Generated by Django 5.2.3 on 2026-08-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0060_flight_evaluation_applied_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalflightevaluation',
            options={'ordering': ['-session_date', '-id'], 'verbose_name': 'Multimotor / Otro', 'verbose_name_plural': 'Multimotor / Otro'},
        ),
    ]
