# Generated by Django 5.2.3 on 2026-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0061_alter_externalflightevaluation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalflightevaluation',
            name='course_type',
            field=models.CharField(default='PCA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='course_type',
            field=models.CharField(default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='course_type',
            field=models.CharField(default='HVI-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='course_type',
            field=models.CharField(default='PCA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='simevaluation',
            name='course_type',
            field=models.CharField(default='PPA-P', max_length=10, verbose_name='Tipo de curso'),
        ),
    ]
