# Generated by Django 5.2.3 on 2026-10-01 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0065_update_flight_instructor_rate_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalflightevaluation',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(5000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation0_100',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(5000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation100_120',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(5000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightevaluation120_170',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(5000)], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='flightreport',
            name='comments',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Comentarios'),
        ),
    ]
