# Generated by Django 5.2.3 on 2025-07-21 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('registration', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('year_manufactured', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('MAINTENANCE', 'En mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='OPERATIONAL', max_length=50)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_cycles', models.IntegerField(default=0)),
                ('max_daily_slots', models.IntegerField(default=3)),
                ('hourly_rate', models.DecimalField(decimal_places=1, default=120.0, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='AircraftAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Aeronave',
                'verbose_name_plural': 'Disponibilidad de Aeronaves',
                'ordering': ['date'],
                'unique_together': {('aircraft', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AircraftHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_flown', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.aircraft')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('aircraft', 'date')},
            },
        ),
    ]
