# Generated by Django 5.2.3 on 2025-07-21 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircrafthours',
            options={'ordering': ['-date'], 'verbose_name': 'Horas de Aeronave', 'verbose_name_plural': 'Horas de Aeronaves'},
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=1, default=130.0, max_digits=4, verbose_name='Tasa horaria'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='maintenance_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('MAINTENANCE', 'En mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='OPERATIONAL', max_length=50, verbose_name='Estatus de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_daily_slots',
            field=models.IntegerField(default=3, verbose_name='Slots máximos por día'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='registration',
            field=models.CharField(max_length=255, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de serial'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_cycles',
            field=models.IntegerField(default=0, verbose_name='Ciclos totales'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_hours',
            field=models.IntegerField(default=0, verbose_name='Horas totales'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='year_manufactured',
            field=models.IntegerField(verbose_name='Año de fabricación'),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.aircraft', verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='hours_flown',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Horas voladas'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='aircrafthours',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horas totales'),
        ),
    ]
