# Generated by Django 5.2.3 on 2025-07-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_standardize_permission_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FPT', 'FPT'), ('B737', 'B737')], max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('hourly_rate', models.DecimalField(decimal_places=1, default=130.0, max_digits=4, verbose_name='Precio por hora')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, verbose_name='Horas totales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Simulador',
                'verbose_name_plural': 'Simuladores',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=1, default=130.0, max_digits=4, verbose_name='Precio por hora'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8, verbose_name='Horas totales'),
        ),
    ]
