# Generated by Django 5.2.3 on 2025-07-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_simulator_alter_aircraft_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='total_cycles',
        ),
    ]
