# Generated by Django 5.2.3 on 2025-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_aircraft_total_cycles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulator',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='simulator',
            name='hourly_rate_dual',
            field=models.DecimalField(decimal_places=1, default=22.5, max_digits=4, verbose_name='$/hora (Dual)'),
        ),
        migrations.AddField(
            model_name='simulator',
            name='hourly_rate_single',
            field=models.DecimalField(decimal_places=1, default=35.0, max_digits=4, verbose_name='$/hora (Simple)'),
        ),
    ]
