# Generated by Django 5.2.3 on 2025-08-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_simulator_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=3.11, help_text='Precio del combustible por litro', max_digits=4, verbose_name='$/Litro'),
        ),
    ]
