# Generated by Django 5.2.3 on 2025-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_aircraft_fuel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_advanced',
            field=models.BooleanField(default=False, verbose_name='Aeronave avanzada'),
        ),
    ]
