# Generated by Django 5.2.3 on 2025-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_aircraft_is_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='hour_correction_factor',
            field=models.DecimalField(decimal_places=1, default=1.3, help_text='Factor de corrección de horas para la aeronave', max_digits=2, verbose_name='Factor de corrección de horas'),
        ),
    ]
